### ISSUE TITLE
Was breaking `-j all` in v0.6.5 intentional?

### ISSUE THREAD

**Issue by fneum** [snakemake/snakemake#1058]
**Snakemake version**
Note the Snakemake version for which you experience the bug.
Always make sure to try out the latest version before creating a new bug report.

0.6.5

**Describe the bug**

Using `snakemake -j all` fails.

I know of the separation of `--cores` and `--jobs` and `snakemake -c all` continues to work. Shouldn't `snakemake -j all` also still work?

**Logs**
If applicable, any terminal output to help explain your problem.

```
snakemake: error: argument --jobs/-j: invalid int value: 'all'
```

**Minimal example**
Add a minimal example for reproducing the bug.

**Additional context**

**Comment by johanneskoester** [comment]
Yes, it was kind of intentional, to keep things simpler in the codebase, and also clean up the semantic in the long run, because -j/--jobs all simply does not make any sense (--cores should be used instead). I hoped to catch most of the old style usages via still supporting --jobs -j without arguments.

**Comment by johanneskoester** [comment]
I will add some more sentences on this in the release notes.

**Comment by johanneskoester** [comment]
Thought about it again. I have now restored the old -j all behavior. It is not that much additional code, and people won't have to update all their readme files.

**Comment by johanneskoester** [comment]
Watch out for the upcoming release.
