### ISSUE TITLE
Is there a standard way to include rust/cargo dependancies in a workflow

### ISSUE THREAD

**Issue by mrvollger** [snakemake/snakemake#1085]
Hello,

I was just wondering if there is a standard way to include rust crates as dependancies in workflows (something similar to the conda yamls)? Sorry if this is already documented, but I couldn't seem find an answer online.

Thanks!
Mitchell

**Comment by dlaehnemann** [comment]
Hi Mitchell,

just came upon this issue on an Rust-related search of the issues.

There is support for using rust-scripts in snakemake, you might have already found that:
https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=rust#rust

Otherwise, I think the best idea probably is to get whatever you are trying to use through snakemake (be it in Rust or any other language) packaged via conda. There is [tooling for Rust conda recipes](https://github.com/search?q=org%3Aconda-forge+rust) on the conda-forge channel and a [Rust team](https://github.com/orgs/conda-forge/teams/rust) with some people that can help.

Hope this helps, and please reopen if you need more info!

Best,
David
