### ISSUE TITLE
Resources with cluster jobs

### ISSUE THREAD

**Issue by troycomi** [snakemake/snakemake#109]
**Snakemake version**
5.7.4+20.gab943e6

**Describe the bug**
When grouping jobs with resources defined, the resources.RESOURCE is taken from the max of the jobs.  However for time it should be the sum of the resource.

**Minimal example**
Using the qsub in tests/test_group_jobs with the following Snakefile:
```
samples = [1,2,3,4,5]

rule all:
    input:
        "test.out"

rule a:
    output:
        "a/{sample}.out"
    group: 0
    resources:
        mem=20,
        time=30
    threads: 2
    shell:
        "touch {output}"

rule b:
    input:
        "a/{sample}.out"
    output:
        "b/{sample}.out"
    group: 0
    resources:
        mem=10,
        time=20
    threads: 1
    shell:
        "touch {output}"

rule c:
    input:
        expand("b/{sample}.out", sample=samples)
    output:
        "test.out"
    group: 1
    resources:
        mem=30,
        time=10
    threads: 3
    shell:
        "touch {output}"

```
Running `snakemake --cluster "echo mem is {resources.mem} ; ./qsub" --jobs 1` produces the following log entry:
```
group job 0 (jobs in lexicogr. order):

    [Thu Nov 14 11:25:05 2019]
    rule a:
        output: a/3.out
        jobid: 9
        wildcards: sample=3
        threads: 2
        resources: mem=20, time=30

    [Thu Nov 14 11:25:05 2019]
    rule b:
        input: a/3.out
        output: b/3.out
        jobid: 4
        wildcards: sample=3
        resources: mem=10, time=20

Submitted group job f0282ae1-97a7-51a9-86f3-7ee58771d003 with external jobid 'mem is 20 threads are 2 time is 30'.
```
Taking the max makes sense for threads and memory, but the time should sum.  I.e. I would expect the last line to be `'mem is 20 threads are 2 time is 50'`

**Additional context**
I'm also wondering how this system deals with a case of:
```
rule a:
  output: {sample}.txt
  resource: mem=100
  threads: 1
  group: 0

rule b:
  input: expand({sample}.txt, sample=range(20))
  resource: mem=100
  threads: 10
  group: 0
```
Will it submit 100 MB with 10 cores, causing 10 instances of rule a to run at once (and use 1 GB)?

**Comment by troycomi** [comment]
I made the title more general because I found another corner case (which is unfortunately important to me).  Taking the above and using a function for resources:
```
samples = [1,2,3,4,5]

rule all:
    input:
        "test.out"

rule a:
    output:
        "a/{sample}.out"
    group: 0
    resources:
        mem=20,
        time=30
    threads: 2
    shell:
        "touch {output}"
def get_mem(wildcards):
    if os.path.exists("a/3.out"):  # random sample
        return 20
    else:
       return 40

rule b:
    input:
        "a/{sample}.out"
    output:
        "b/{sample}.out"
    group: 0
    resources:
        mem=get_mem,
        time=20
    threads: 1
    shell:
        "touch {output}"

rule c:
    input:
        expand("b/{sample}.out", sample=samples)
    output:
        "test.out"
    group: 1
    resources:
        mem=get_mem,
        time=10
    threads: 3
    shell:
        "touch {output}"
```

The execution is random, but in cases where rule b, sample 3 runs early, I would expect subsequent submissions of rule b to return 40 for mem.  Instead, it seems like the dag is caching the resource value on jobs that can run and using (possibly) outdated values for submissions.  Rule c uses 40, so the update to 'can_run' triggers the resources to evaluate.

I would like the resources to be evaluated immediately before doing the cluster format for submission.  Would removing [this line](https://github.com/snakemake/snakemake/blob/5dfac1565cb856077ce2220beb9ee84dfec81c1b/snakemake/jobs.py#L264) be too much of a performance hit?

Since this is abstract, the reason I need this is I'm working on regressing the memory and time usage based on input file sizes.  As jobs finish I can update my model to submit better estimates for resources.  With the current implementation, if I have 1000 jobs running 250 at a time, the same model is used for all 1000 jobs instead of updating it.

**Comment by bnprks** [comment]
I have run into this issue as well, and I would propose that the job_properties dictionary for group jobs be expanded to include list of the component jobs within that group that will be run (at a minimum the resources+threads for each job, but wildcards, rule names, and params could also be useful). Then a user's cluster submission scripts can be customized if needed to handle group jobs differently from snakemake's default handling.

My logic for this is that whether to sum, take the max, or do otherwise with resources is highly situation dependent. For example, in typical usage it would make sense to sum time resources and take the max of memory usage + threads. However, I am working on group jobs that use named pipes for output, in which case all jobs in the group will run concurrently. In the case with named pipes, it makes more sense to take the max of time and the sum of memory usage + threads (the reverse of typical usage).

**Comment by SilasK** [comment]
It seems that there are many use cases for groups on clusters/clouds and that they cannot be solved in the cluster_wrappers. 

It seems almost that one would need a snakemake in a snakemake to deal with all the situation. 

Maybe Subworkflows could solve the problem #791 

For completeness. My use case is again somewhat different from what is mentioned above.

What I would like to do is group many jobs that use the same db together. The jobs have a high memory and cpu usage but run quite fast 5 min. 

My idea was that:

1. Copy the db in the shared memory
2. Run the jobs that access the db one after the other
3. final rule that assures that all jobs belong to the same group

I've seen that all jobs are executed simultaneously. This is not what I need.

**Comment by fischuu** [comment]
On a related matter, I think Snakemake currently combines the resources for group jobs only if they are defined in the` resources` section of the grouped rules. However, if they are defined in a server_config.yaml file, the group job takes onle the `__default__` resources.

As a workaround I currently create a dictionary within the snakefile like this

```
import yaml
import os,sys

cluster=dict()
if os.path.exists("server_config.yaml"):
    with open("server_config.yaml") as yml:
        cluster = yaml.load(yml)
```

and then add for each rule the following resource allocation

```
    resources:
        mem=cluster["rule1"]["mem"]
```

and then in the `--cluster` option I write `--mem-per-cpu={resources.mem}` instead of `--mem-per-cpu={cluster.mem}` .

However, this seems rather laborious to put the whole cluster configuration first into a central yaml file, then collect the data into the individual rules and then move them again back to the snakemake call. 

Would it be possible that the group job combines the resources also when they are defined in a yaml file without the extra step to collect them into the resource section of the corresponding rules?

**Comment by johanneskoester** [comment]
@fischuu server_config (or rather cluster config) is deprecated and resources should be used instead (see docs).

For the general issue, this has been fixed in the meantime. Groups are now toposorted and resources of parallel jobs are summed.
