### ISSUE TITLE
Support for GPU ressources

### ISSUE THREAD

**Issue by arn-all** [snakemake/snakemake#116]
**Is your feature request related to a problem?**
On a machine that has both several GPUs (let's say 4) and several CPUs/therads, there is no way to specify which GPU resources you want to allocate to your jobs.

For example, I often want 4 jobs to run on each GPU of the machine (4 on number 1, 4 on number 2,...). Conversely, I can't schedule jobs with "N different CPU threads AND N GPU" for each job. 

**Describe the solution you'd like**
Some way to specify either : 
1. how many jobs a GPU can handle (1GPU, different parallel jobs)
2. how many GPUs are needed by a job (1 job, several GPU)

It would be convenient to have a `{gpu}` tag similar to the existing `{threads}` 

**Describe alternatives you've considered**
The documentation for "Resources" briefly mentions hybrid CPU/GPUs architectures :

> Apart from making Snakemake aware of hybrid-computing architectures (e.g. with a limited number of additional devices like GPUs) this allows to control scheduling in various ways, e.g. to limit IO-heavy jobs by assigning an artificial IO-resource to them and limiting it via the --resources flag. Resources must be int values.

But I don't think it's what I'm looking for. More specifically, I'd need to tell my shell command which is the ID of the GPU it has been assigned to 

**Additional example**
An example usage with the software lammps that requires 1 CPU per job and allows up to 4 jobs per GPU would look like :

```
rule foo:
    input:
        "bar"
    output:
        "egg"
    threads: 1
    jobs_per_gpu: 4
    run:
        shell("lmp_gpu -sf gpu -pk gpu 1 gpuID {gpu} {gpu} -in input.txt")
```
Starting 7 jobs at the same time on a 2-GPUs machine would result in 4 with {gpu} = 0 and 3 with {gpu} = 1

I understand that it can be very complicated to implement, especially knowing that there can be other jobs / other programs that use the GPUs at the same time than my rule. I'd be happy to just use a hack that would do what I'm looking for without needing changes in snakemake, if there is any ? 

Thanks a lot for your great work on that project !

**Comment by troycomi** [comment]
This is asking for a couple of things which I *think* snakemake can handle out of the box with varying amounts of clunky-ness.
- Local execution
  - 'Partial' gpus.  This can be accomplished by turning the resource around and calling it something like gpu_shares.  In your example (if that were your only rule) you could invoke snakemake with 8 available shares for 2 GPUs and each job would use 1.  If you had another rule that could only do 2 jobs per gpu it would take 2 shares.  Depending on how divisible those numbers are you would need some silly number of shares, e.g. jobs that could support 2, 3, and 5 shares would need each GPU divided into 30 parts.
  - Getting GPU id.  The only hack I can come up with is to use some python code to track how many jobs are on a GPU.  Without testing, I'm thinking something like:
```
gpus = 2
gpus_used = [ [] * gpus]
rule foo:
    input:
        "bar"
    output:
        "egg"
    run:
        my_id = # generate a unique id for this job, probably a guid or random number
        for i in range(len(gpus_used)):
           if len(gpus_used[i]) < 4:
              my_gpu = i
              gpus_used[i].append(my_id)  # add id to indicate that gpu is in use
              break
        shell("lmp_gpu -sf gpu -pk gpu 1 gpuID {my_gpu} {my_gpu} -in input.txt")
        gpus_used[my_gpu].remove(my_id)  # release resource
```
This depends on snakemake limiting how many jobs are running at once through the resources defined above.  It may break due to variable scoping or threading issues that may require a mutex for changing gpus_used list.  I would stick to cluster execution :smile: 
- Cluster execution.  This is easier because the scheduler will take care of getting you an exclusive GPU. You can use groups to get your 4 jobs running on one GPU.  Your workflow will require a dummy rule to group together 4 of your GPU jobs similar to [this](https://bitbucket.org/snakemake/snakemake/issues/967/batch-together-small-jobs-in-cluster)
  - Partial gpus. The job grouping of your dummy rule will determine how many rules are submitted in a single job.  Make sure you provide the group job with 4 cores to run the 4 rules simultaneously.
  - Getting GPU id.  The shell command in your rule can include any valid bash commands.  In a cluster environment, you can query the appropriate library to get the id in a subprocess command.  E.g. replace {gpu} with $(<COMMAND>) using something from [here](https://askubuntu.com/questions/5417/how-to-get-the-gpu-info).  However, I think when the scheduler allocates a job the GPU id will start at 0 anyways so you can use that value for all 4 jobs in a group.

Certainly not the best solution but it may get you running while waiting for an enhancement.  I think this could more generally be phrased as support for shared or partial resources.  Hope that helps!

**Comment by arn-all** [comment]
Thanks a lot. Using the cluster solution, I finally came up with the following snakefile :

```
import hashlib

jobs_per_gpu = 3

# The parameter I want to test
seeds = [str(x) for x in range(101, 110)]

# the files I want to have at the end of my calculation
def final_file(seed):
    return "finished_s{}.log".format(seed)

# split all the jobs in groups of len <= jobs_per_gpu
groups = [seeds[i:i+jobs_per_gpu] for i in range(0, len(seeds), jobs_per_gpu)]

def filelist_to_hash(files):
    return hashlib.md5('-'.join(files).encode('utf-8')).hexdigest()[:8]

rule aggregate_cells:
    input: [final_file(seed) for seed in seeds]
    output: touch("intermediate/all-aggregated-flag")
    shell: "echo 'Finished' "  # yay !

for group_ in groups:
    for seed in group_:
        rule:
            params: seed = seed
            output: final_file(seed)
            group:  filelist_to_hash(group_)
            run:
                shell("echo {params.seed}; sleep 2; touch {output}") # you can do your calculation here 
```

That I managed to start 3 by 3 with the following command : 

`snakemake --cluster '' -j 3`

Thanks a lot, I would never have managed to solve it without help !

**Comment by arn-all** [comment]
Actually my previous (now deleted) post was not doing what I wanted to.  I realised also that my approach was too complicated. Yet, the new one is still super-clunky. Though it finally does what I was looking for.

In case someone would arrive here from a search engine, looking for a way to group small jobs or to run on GPUs (as I saw there were few other issues on that topic), here is what I finally came up with :

```python

configfile: "config.yaml"

def split_list(mylist, group_length):
    ## Splits a long list into a list of shorter list. The short lists have len <= group_length
    return [mylist[i:i+group_length] for i in range(0, len(mylist), group_length)]

def filelist_to_hash(files):
    ## takes an array of (str) filenames, returns a unique (str) hash
    return hashlib.md5('-'.join(files).encode('utf-8')).hexdigest()[:8]

# The inputs of rule "all"
finals = expand("simulation_output_{a}-{b}.txt",
        a=config["a_list"],
        b=config["b_list"])

groups = split_list(finals, config["jobs_per_gpu"])

rule all:
    input:
        finals,
        [filelist_to_hash(group) for group in groups]
    output:
        "reports/results.h5"
    script:
        "results-analysis.py"


for group in groups:
    ### Anonymous rules to link jobs of a same group, so the --cluster
    ### directive executes them all together on a node (subgraph)
    rule: 
        input:
            group
        output:
            temp(touch(filelist_to_hash(group)))
        group:
            "batch_jobs"

rule shear:
    ## my actual simulation
    input:
        "some_intermediate_file_{a}{b}.lmp"
    output:
        "simulation_output_{a}-{b}.txt"
    group:
        "batch_jobs"
    run:
            shell("lmp_gpu -sf gpu -pk gpu 1 gpuID 0 0 neigh no -in {wildcards.b}")
```

If you have any further comment just let me know. 

Thanks for your help !

**Comment by Emiller88** [comment]
@arn-all This might be worth adding to the docs.
