### ISSUE TITLE
A utility function to partially format strings with wildcards

### ISSUE THREAD

**Issue by shenghuanjie** [snakemake/snakemake#124]
**Is your feature request related to a problem? Please describe.**
In the workflow, we usually need to deal with multiple wildcards.
It would be nice if there is a function to partially format the input string with multiple wildcards.
Maybe this function already exists and I'm just not aware of it.
For example:
```
foo = "{a}_{b}.txt"
result = format_cards(foo, a="foo")
print(result)
# result = "foo_{b}.txt"
```

**Describe the solution you'd like**
Here is a [solution](https://stackoverflow.com/questions/11283961/partial-string-formatting) I found on StackOverflow.
```
def format_cards(template, **kwargs):
    import string
    class FormatDict(dict):
        def __missing__(self, key):
        return "{" + key + "}"
    formatter = string.Formatter()
    mapping = FormatDict(**kwarg)
    return formatter.vformat(template, (), mapping)
```

**Comment by troycomi** [comment]
I may take that format cards function because it is cleaner than the methods I know.  Here are some other workarounds if others are looking for base python ways to do this:
- `result.replace('{a}', 'foo')`  # gets gnarly with additional wildcards to replace
- `"{a}_{{b}}.txt".format(a="foo")`  # hard to use if paths are in config
- `"%s_{b}.txt" % "a"`  # won't play nice with wildcards

Would an acceptable solution be to include an optional keyword argument in expand (say `allow_missing`) which would keep missing wildcards as just wildcards?  You could call the replace the above with: `expand(foo, a="foo", allow_missing=True)`.  It would keep the other functions of expand and be more of a drop-in replacement.  If allow_missing wasn't included or had a value of not true, expand would have the typical operation, maintaining backward compatibility.

If that sounds good I can work on a PR.  Clearly I don't have good workarounds!

**Comment by shenghuanjie** [comment]
> I may take that format cards function because it is cleaner than the methods I know. Here are some other workarounds if others are looking for base python ways to do this:
> 
> * `result.replace('{a}', 'foo')`  # gets gnarly with additional wildcards to replace
> * `"{a}_{{b}}.txt".format(a="foo")`  # hard to use if paths are in config
> * `"%s_{b}.txt" % "a"`  # won't play nice with wildcards
> 
> Would an acceptable solution be to include an optional keyword argument in expand (say `allow_missing`) which would keep missing wildcards as just wildcards? You could call the replace the above with: `expand(foo, a="foo", allow_missing=True)`. It would keep the other functions of expand and be more of a drop-in replacement. If allow_missing wasn't included or had a value of not true, expand would have the typical operation, maintaining backward compatibility.
> 
> If that sounds good I can work on a PR. Clearly I don't have good workarounds!

Hi @troycomi, having `allow_missing` is exactly something I'm looking for.
The reason why I request this function is because it's very helpful in the input function where some wildcards are determined from the output while others are searched and filled in.
For instance, the workflow below:
```
rule all:
    input:
        'all.done'

def get_inputs(wildcards):
    # wildcards: {"a": "something"}
    # fill in wildcards from the output here with the partial formatting function
    filename = format_cards("input/{a}_{b}.txt", **dict(wildcards))
    # list the files of the given output wildcard
    return [x[0] for x in snakemake.utils.listfiles(filename)]

# input file has format {a}_{b}.txt and {a} {b} don't contain '_'
rule step1:
    input:
        get_inputs
    output:
        touch("output/{b}.txt")

def get_files(wildcards):
    # here is an example where values of {b} are filled in by searching the input folder
    # sometimes it's determined from a metadata file.
    allcards = glob_wildcards("input/{a}_{b}.txt")._asdict()
    return expand("output/{b}.txt", **allcards)

rule step2:
    input:
        get_files
    output:
        touch("summary.txt")
```

Maybe there is also a better way to write a workflow like this that I'm not aware of.  But this is a general one I write every day where partial formatting would be very helpful.

**Comment by troycomi** [comment]
Just made a PR.  Review if you have time!
