### ISSUE TITLE
Namedlist set_name overrides class functions ( for example --report  crashes if a params: variabel is called 'items')

### ISSUE THREAD

**Issue by Gutorm** [snakemake/snakemake#143]
**Snakemake version**
5.7.4 
**Describe the bug**
`snakemake --report` will crash if one of the `params:` is called "items" (see example below)
(snakemake workflow execution has no problem with this, only `--report`)

This is probably due to `items()` being a method of python 

**Logs**
(Corresponds to example below)
```
snakemake  --report
Building DAG of jobs...
Creating report...
Adding foo.rst (0 MB).
Could not detect mimetype for foo.rst, assuming text/plain.
Traceback (most recent call last):
  File "/mnt/work/Qc.py375.venv/lib/python3.7/site-packages/snakemake/__init__.py", line 618, in snakemake
    batch=batch,
  File "/mnt/work/Qc.py375.venv/lib/python3.7/site-packages/snakemake/workflow.py", line 617, in execute
    auto_report(dag, report)
  File "/mnt/work/Qc.py375.venv/lib/python3.7/site-packages/snakemake/report/__init__.py", line 552, in auto_report
    FileRecord(f, job, report_obj.caption, env, category)
  File "/mnt/work/Qc.py375.venv/lib/python3.7/site-packages/snakemake/report/__init__.py", line 326, in __init__
    self.params = logging.format_dict(job.params)
  File "/mnt/work/Qc.py375.venv/lib/python3.7/site-packages/snakemake/logging.py", line 384, in format_dict
    for name, value in dict.items()
TypeError: 'str' object is not callable
```

**Minimal example**

```python
rule test:
  output: report(touch("foo.rst"))
  params: items = "hello darkness"
  run:
      print (params[0])
```
 

**Additional context**
Note that `  params: foo = "hello darkness"` will work.

)

**Comment by troycomi** [comment]
At first I was thinking, "why would you override a builtin function?" but the actual cause is more of a problem.  The params, along with most directives, are stored as a Namedlist, defined in [io.py](https://github.com/snakemake/snakemake/blob/master/snakemake/io.py#L1120).  When a value is [set](https://github.com/snakemake/snakemake/blob/master/snakemake/io.py#L1170), it sets the attribute for the name provided ('items') overriding any functions.  You can also break this with params like 'set_name' or resources called 'items', which causes crashes on execution.  Oddly setting an output file as items="foo.txt" doesn't cause the same crashes.

I'm surprised this hasn't come up sooner.  A better name for the issue would be "Namedlist set_name overrides class functions".

[addict](https://github.com/mewwts/addict/blob/62aec341d12ebbe313a67ce63838202ba9d9e742/addict/addict.py#L24) just prevents the setting of any attribute which already exists, though I'm not sure if that would break updating or some existing workflows.  I'll submit a PR to do the same thing as addict and print the following error on snakemake execution:
```
AttributeError in line 6 of Snakefile:
Namedlist attribute 'items' is read only.  Cannot set to 'hello darkness'
```
once the local tests finish.

**Comment by Gutorm** [comment]
Thanks @troycomi  - I have changed the title - I was not aware of the underlying reason. Also being pretty new to snakemake (and python) I must admit that I picked  a variable name that happens to be a method - it was not like i  _wanted_ to override anything :-)

**Comment by troycomi** [comment]
Welcome to python and snakemake then!  I was thinking of other instances where people had used variable names like `directory` which caused a similar error message when trying to use the `directory` snakemake file decorator.  What was odd in this case is the scope of the variable seemed wrong; setting a params like `join` would be fine.

Thanks for finding this bug!
