### ISSUE TITLE
Snakemake profile parameter in API

### ISSUE THREAD

**Issue by dominikburri** [snakemake/snakemake#1488]
**Is your feature request related to a problem? Please describe.**
Not sure if I miss something, but using the snakemake API does not allow to pass a profile file path. I assumed that I could pass a profile just like a Snakefile or cores as arguments in command line, but also as parameters in a python call. 

So, 
```bash
snakemake --profile slurm
```
would work, but this won't:
```python
import snakemake
snakemake.snakemake(profile = "slurm")
```

Is this intended?

**Describe the solution you'd like**
Ideally, the API allows `profile` as parameter. 

**Describe alternatives you've considered**
Alternatively, a system call within python would do the job or setting the environment variable `SNAKEMAKE_PROFILE`.

**Comment by pvandyken** [comment]
Profiles are interpreted using the cli parser, the code for which is found in snakemake.main() (in `snakemake/__init__.py`. `snakemake.snakemake()` doesn't have a profile parameter because the profile should already be parsed by the time it's called. I doubt including `profile` as a parameter would ever be supported. If anything, the parser could be isolated as a separate callable returning some class (e.g. `SnakemakeArgs`) that could then be passed into `snakemake.snakemake`. But this would involve a fair amount of refactoring.

The best workaround currently is to call `snakemake.main(["arg1", "arg2", etc...])`, passing all your options as CLI strings. It's not so clean from an API perspective, but it's better than a subprocess call.

**Comment by dominikburri** [comment]
Hi @pvandyken, thank you for the response! 
Totally agree and thanks for the `snakemake.main()` pointer, I was not aware of this.
