### ISSUE TITLE
Namedlist attribute 'index' is read only

### ISSUE THREAD

**Issue by tpall** [snakemake/snakemake#151]
**Snakemake version**
5.8.1+12.g85a09c4

**Describe the bug**
Parameter assignment is broken in snakemake wrapper, seems to happen after commit ba4cc28448.

**Logs**
```bash
$ snakemake --use-conda -n
AttributeError in line 16 of <redacted>/snakemake-wrappers/bio/bwa/mem/test/Snakefile:
Namedlist attribute 'index' is read only.  Cannot set to 'genome'
  File "<redacted>/snakemake-wrappers/bio/bwa/mem/test/Snakefile", line 16, in <module>
```

**Minimal example**
Can be reproduced by running bio/bwa/mem/test/Snakefile from snakemake-wrappers repo. 

**Additional context**
Haven't tested other wrappers. In my workflow, first rule using snakemake/snakemake-wrappers wrapper (which happened to be bio/bwa/mem) started to throw this error. Test case is shown below. 

```bash
rule bwa_mem:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
    output:
        "mapped/{sample}.bam"
    log:
        "logs/bwa_mem/{sample}.log"
    params:
        index="genome",
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sort="none",             # Can be 'none', 'samtools' or 'picard'.
        sort_order="queryname",  # Can be 'queryname' or 'coordinate'.
        sort_extra=""            # Extra args for samtools/picard.
    threads: 8
    wrapper:
        "master/bio/bwa/mem"
```

**Comment by troycomi** [comment]
That's kind of an intended exception.  The commit fixed a bug where attributes in the params list would override member functions of the same name.  If those functions are never called there wasn't an issue.  However, there wasn't any indication on assignment and an error would only pop up after that method was attempted to be used.  Namedlist (which params inherits from) is a subclass of list, so index and sort are no longer valid param names.

The change clearly breaks some old code, but if a feature was added that used the list functions sort or index it would break all the same code.  In the end, different names have to be used.

@johanneskoester is this still a good change?  We could make the check optional to ease the transition, change the exception to a warning, or try to catch this when an overridden function is called instead of on assignment.

**Comment by tpall** [comment]
Thanks! Fortunately, according to manual, bwa mem uses db.prefix argument.
 
Changing "index" and "sort" params in bio/bwa/mem wrapper to "db_prefix" and "sorting", respectively, fixed the problem. 
Alternatively, "ref" could be used instead of index. 

Other bwa wrappers are affected too.

**Comment by troycomi** [comment]
I opened an issue on the wrappers repo as it's more of an issue there.  We should keep this open in case Johannes wants to deal with this differently than refactoring all the wrappers.
