### ISSUE TITLE
--report: Category is prone to ... stuff

### ISSUE THREAD

**Issue by Gutorm** [snakemake/snakemake#155]
**Snakemake version**
5.74
**Describe the bug**
If `category` contains characters like '.',  '(' or ')' (and probably some other chars), the results will be hidden from view

**Logs**
NA
**Minimal example**
 ```
rule one:
        output: report(touch("oneDone"), category="Module 1.1")
        run: print (output)
```
`snakemake -f one; snakemake --report`
**Additional context**
The `category` link will be visible under the Results section of the html file.  Alas, clicking on it will not make it expand to show results (normal behaviour). 

Obviously not important - but it could be documented, or could hide something more serious.

**Comment by johanneskoester** [comment]
First of all, sorry for the late response. After many new features, Snakemake is approaching feature completeness (at least for my personal agenda and at the moment). Hence, now is the time to fix or close all the open bugs.

This has been recently fixed with the latest release, providing a complete report rewrite. I have just checked your example and it now works fine.
