### ISSUE TITLE
forcerun has no effect

### ISSUE THREAD

**Issue by Zepeng-Mu** [snakemake/snakemake#1852]
Using snakemake 7.14.0, it seems that `forcerun` has no effect unless I also specify the output files in `rule all`. But using previous version, specify intermediate output files is not necessary becuase later rules depend on these files.
For 7.14.0, I'm getting something like this:

```sh
$ snakemake -np -s 02.01_glimpse_scATAC.smk --forcerun compute_GL --quiet                
Building DAG of jobs...
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
all                     1              1              1
concat                  1              1              1
filter_vcf              1              1              1
fmt_1kg                 1              1              1
plotCoverage            1              1              1
reheader_bam_chr       10              1              1
rename_chr              1              1              1
total                  16              1              1
```
I do expect to see `compute_GL` in the jobs. Also, `forceall` has no effect either. Maybe this is not a bug but the behavior is different from previous versions, so I'm not sure how to force a rule to run.

Thanks.

**Comment by Zepeng-Mu** [comment]
Turned out that one of my input files is missing, and snakemake does not through an error.
When I deleted the output of that rule, snakemake did through an error, that how I realized the input file is missing.

**Comment by tbooth** [comment]
When the input file is missing but the intermediate file is there Snakemake just assumes that the intermediate file *is* the original input file (since it doesn't know any better), even if there is a rule available that could potentially make that file.

I have wondered myself if Snakemake would be easier to use if the logic applied was to follow the chain of rules all the way back and then insist that the first input files must be present, but even if that were implemented it would have to be as special new option, so it would be an enhancement request.

So I don't think this is a bug. @Zepeng-Mu, may we close the bug report?

**Comment by Zepeng-Mu** [comment]
I agree that when the intermediate file is there, snakemake does not need to check whether the original input file is there.

In my case, I was trying to forcerun to update the intermediate file, and I expect snakemake to tell me that the original input files were missing. But this did not happen until I deleted the intermediate files.

But I should have the original input files in place before updating the intermediate files, so I agree this may not be a bug the behavior is a bit unexpected.
