### ISSUE TITLE
Set global constraint for the number of cores

### ISSUE THREAD

**Issue by fgroll** [snakemake/snakemake#1863]
**Is your feature request related to a problem? Please describe.**
In cluster mode, to keep jobs that use a large number of cores and/or run for a long time from using up all available computing resources of our cluster and thereby preventing other people from running their jobs, we would like to limit the total number of cores used by a single Snakemake workflow.
Version 7.11 of Snakemake introduced resource scopes to constrain the usage of resources either on a per-job basis ('local') or across all jobs within a Snakemake workflow ('global'). The only resource that can't be defined as a global constraint is `threads`. 

**Describe the solution you'd like**
Allowing the scope for `threads` to be set to 'global' through the `resource_scopes` directive and the `--set-resource-scopes` option could allow to constrain the maximum number of cores per workflow by setting the `--cores` option.

**Describe alternatives you've considered**
A rather simple workaround for this is to add a resource to each job that mirrors the number, called `cores` for example. By default, this `cores` resource will have a global scope and can be constrained through `--resource cores=X`. This works fine, but it seems repetitive having to set the number of threads used in `threads` and additionally as `resource`.

**Additional context**
I am not sure whether using `--cores` is not intended to constrain the total number of cores used in Snakemake's cluster mode, but to me it would reflect the functionality of `--cores` when run locally.

**Comment by pvandyken** [comment]
@fgroll, I think this is technically already possible, albeit not documented or user-friendly. Under the hood, `threads` is saved as `_cores`, so by setting `--set-resource-scopes _cores=X`, you should be able to achieve this. 

In principle we could add an alias to make this easier. One concern, though, is that it's not currently possible to have both a global and local limit to the same resource. So if you had a global core limit of 100 cores, and each cluster allowed 20, you can't set `--cores=100` because then Snakemake would request 100 cores from a single node.

A few workarounds I can think of
- Use `--jobs` to limit the number of jobs submitted at a time. In principle, this times the number of `--cores` would be equivalent to a global limit on cores.
- Use a dummy resource `cores` as suggested, but set it to `lambda wcards, threads: threads`. Unfortunately, `--default-resources` doesn't support lambdas currently, but at least you could copy/paste

I'd appreciate your feedback specifically on the first suggestion: it seems to me that equivalence should hold always, but maybe you have an example where it wouldn't?

**Comment by pvandyken** [comment]
For what it's worth, I've proposed an API to allow setting both the global and local scope for a resource #1910

**Comment by fgroll** [comment]
Hey, thanks for the extensive answer! I have tried your suggestions, to see which feels the like the best compromise:
- Trying to set the scope for `_cores` results in an error: `Invalid resource scopes: entries must be defined as RESOURCE=SCOPE pairs, where SCOPE is either 'local', 'global', or 'excluded' Unparseable value: '_cores'.`.
- If I understand correctly, combining `--jobs` with `--cores` results in a different behaviour when limiting the global number of cores. In a workflow involving jobs with different numbers of cores running at the same time, setting `--cores` to the lower number of cores is necessary to maximize the number of jobs run in parallel. This would mean jobs that can make use of more cores efficiently would run slower. On the other hand, setting a global resource limit could result in fewer parallel jobs than possible, when the limit is not a multiple of the cores per job. But to me, setting a global resource limit seems to be the less hands-on approach.
- Using `cores = lambda _, threads: threads` combined with `--resources cores=X` works and at least helps to prevent setting `threads` and `cores` to different values.

In the end, I think your proposal to set global and local resource limits combined with the ability to set a global limit for cores would be the most comprehensive solution.

**Comment by pvandyken** [comment]
> Trying to set the scope for _cores results in an error: Invalid resource scopes: entries must be defined as RESOURCE=SCOPE pairs, where SCOPE is either 'local', 'global', or 'excluded' Unparseable value: '_cores'.

Woops, apologies. I guess snakemake doesn't like parsing `_underscore` resources.

> If I understand correctly, combining --jobs with --cores results in a different behaviour when limiting the global number of cores. In a workflow involving jobs with different numbers of cores running at the same time, setting --cores to the lower number of cores is necessary to maximize the number of jobs run in parallel. This would mean jobs that can make use of more cores efficiently would run slower. On the other hand, setting a global resource limit could result in fewer parallel jobs than possible, when the limit is not a multiple of the cores per job. But to me, setting a global resource limit seems to be the less hands-on approach.

I think I understand what you mean, but let me try to phrase it and see. My suggestion for `--jobs` is to not have any global constraint on `--cores` at all (so no extra dummy resources, etc). So if some jobs need 32 cores, some need 16, and some need 8, you set `--cores=32`. Snakemake will only request the actual number of cores needed for each submitted job. To limit global cores, you set `--jobs=5` or whatever, and that guarantees that only `5*32` global cores will be used at one time. However, I think you're saying that this will unnecessary stifle the jobs that need 8 cores, as when they run, only `5*8` cores will be used. Is this correct?

If so, you could use `--group-components` to push multiple of these 8 core (or whatever) jobs into the same submission. That way each submission would still use 32 cores (or whatever) each and you'd keep your core usage at `5*32`.

Hope that makes sense... just trying to gauge if we need to implement a way to limit global core usage, or if there's a good workaround already.

**Comment by fgroll** [comment]
That's exactly what I was trying to say, with `--cores=32` and `--jobs=5`, only 5 jobs using 8 cores would be submitted, instead of a possible 20.

As I have never used job grouping before, I wasn't aware that there is an option to group jobs in that way. From looking at the documentation, it seems that using `--group-components` requires the jobs to be in the same group, is that correct? So to make the best use of the cluster, a command like `snakemake --group-components cores8=4 cores16=2` could be used, where all jobs that use 8 cores are in the group 'cores8' and all jobs using 16 cores are in the group 'cores16'.
In that case, using `--cores`, `--jobs` and `--group-components` would probably work just as well as adding `resources: cores = lambda _, threads: threads` to each job.

In the end, for me personally using the workaround of setting a globally limited `cores` resource for each job works well enough. Therefore, implementing a way to use `threads` for limiting global core usage would definitely be more a convenience than necessity.

**Comment by pvandyken** [comment]
> As I have never used job grouping before, I wasn't aware that there is an option to group jobs in that way. From looking at the documentation, it seems that using --group-components requires the jobs to be in the same group, is that correct? So to make the best use of the cluster, a command like snakemake --group-components cores8=4 cores16=2 could be used, where all jobs that use 8 cores are in the group 'cores8' and all jobs using 16 cores are in the group 'cores16'.

Yeah, exactly. The only other thing is that jobs in the same group need to be "adjacent" to each other in the workflow. In practice, what I do is put every single rule into a group, usually grouping rules based on compatible resource usage, but sometimes a group will just have a single rule. Then I set `group-components` in my profile so that it applies for every run. The advantage is that I can calibrate the group sizes to get the runtime exactly how I want, e.g. so that I can target the 3hr or 6hr job length window on my cluster. 

Also, was playing around with it a bit more, and realized you can actually just use `--default-resources cores=threads`. Snakemake treats strings assigned to default resources as the body of the resource lambda (this is actually not explicitly documented). That saves you from typing the lambda every single time. (at least, this worked on a small test workflow)

Overall, given these two independent methods (`--cores`+`--jobs`+`--group-components` and `--default-resources`), I would say being able to set a global constraint for cores is already possible. I'd say this issue can be closed, but let me know if you have any more thoughts.

**Comment by fgroll** [comment]
From testing with my small test workflow, `--default-resources cores=threads` works perfectly fine. Even better, adding `default-resources: "cores=threads"` to the `config.yaml` used in my profile for submitting jobs to the cluster, I can simply restrict the total number of cores with `--resources cores=5`. To me that's the perfect solution without requiring any changes to snakemake.

I think it might be useful to document this somewhere, but I am not sure in which part of snakemake's documentation it would best fit. Maybe as an example for an updated documentation of `--default-resources`, as you mentioned in #1707 ?

Thanks again for your help, this has not only solved my problem but also helped me understand snakemake a bit better!
