### ISSUE TITLE
`touch` does not work inside `run` directive

### ISSUE THREAD

**Issue by dariober** [snakemake/snakemake#1982]
**Snakemake version**: 7.18.2

**Describe the bug**

The `touch` command does not work when used in the `run` directive and it does not throw an error either.

**Minimal example**

```
rule all:
    input:
        'test.txt'

rule one:
    output:
        x='test.txt'
    run:
        touch(output.x)
```

I would expect `touch` to either create `test.txt` or give an error that `touch` cannot be used in `run`. Instead I get a missign `MissingOutputException`:

```
snakemake -p -j 1
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
one          1              1              1
total        2              1              1

Select jobs to execute...

[Wed Nov 30 11:34:51 2022]
rule one:
    output: test.txt
    jobid: 1
    reason: Missing output files: test.txt
    resources: tmpdir=/tmp

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
Waiting at most 5 seconds for missing files.
MissingOutputException in rule one  in line 5 of /home/dario/Downloads/Snakefile:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
test.txt completed successfully, but some output files are missing. 0
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-11-30T113450.882315.snakemake.log
```

**Comment by tbooth** [comment]
The same would be true of the `protected()`, `temporary()` and `ancient()` functions. All of these just take a filename and add a flag for the workflow engine to interpret. The `touch()` function itself does not touch any file - it just signals Snakemake to do so when it sees a "touched" file as a rule output.

I don't see an easy fix for this - `touch()` is a very simple function and having it introspect its calling context to detect when the result is not being used would be very hacky. Other languages have standard ways of warning when a function result is not assigned but Python (by design) just assumes you never cared. It's a bit like calling `sorted(mylist)` instead of `mylist.sort()` and then wondering why the list is still in the same order - a classic Python gotcha.

Probably the function should have been named `touched()` instead of `touch()` to show that it's an adjective and not a verb, but I don't think there is any reasonable possibility of changing the name by now.

**Comment by dariober** [comment]
@tbooth thanks for the explanation - happy to close the issue then. Regarding this though:

> The touch() function itself does not touch any file

A rule like this:

```
rule done:
    output:
        touch('done.txt')
```

does create the file `done.txt` so I thought `touch` does something more than adding a flag and therefore should work inside the `run` directive. Anyway, it's no big deal.

**Comment by tbooth** [comment]
Thanks for closing the issue, @dariober, but since you asked I'll try to illustrate what is happening. The Snakemake order of operations is not very intuitive!

Try running the following Snakefile:

~~~
# Test for @dariober.
# Run: $ snakemake -j1 -F done_1.txt done_2.txt

def my_touch(file_template):
    """Wrap the touch() function to show when it gets called.
    """
    print(f"Running touch({file_template!r})...")
    result = touch(file_template)
    print(f"it returned {type(result)} with flags {result.flags}")
    return result

rule done:
    output:
        my_touch('done_{n}.txt')
    run:
        my_touch('this_will_not_be_created.txt')
~~~

Note that the `touch()` function is never actually called on `done_1.txt` or `done_2.txt` - it's called on the template `done_{n}.txt`. Because your original example has no wildcards the distinction isn't obvious. As I said above, the `touch()` function does not itself touch files - rather Snakemake sees the `touch=True` flag attached to the template in the rule definition, expands the template with the specific wildcards for the job that is executing, and only then it creates the files.

Hope that helps.
\- TIM
