### ISSUE TITLE
Difference in configfile behavior between API and CLI

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakemake#214]
**Snakemake version**
5.10.0

**Describe the bug**
This command

```
 snakemake  --google-lifesciences --verbose --default-remote-prefix snakemake-testing/kim-wxs-varlociraptor-1 --use-conda --google-lifesciences-keep-cache --google-lifesciences-region us-west1
```

produces a config!

```
<snakemake.workflow.Workflow object at 0x7f8613cc3d30>
>>> workflow.configfiles
['config/config.yaml']
```

This command (from Python) does not:

```
cores = 3
verbose=True                                                                                                                  
success = snakemake(
    snakefile,
    cores=cores,
    workdir=tmpdir,
    stats="stats.txt",
    use_conda=True,
    google_lifesciences_regions=["us-west1"],
    default_remote_prefix="snakemake-testing/%s" % name,
    google_lifesciences=True,
    google_lifesciences_cache=True,
    verbose=True)
```

**Probably related:**

Thoughts by @vsoch:

```
    def configfile(self, fp):
        """ Update the global config with data from the given file. """
        global config
        self.configfiles.append(fp)
        c = snakemake.io.load_configfile(fp)
        update_config(config, c)
        update_config(config, self.overwrite_config)
```

in workflow.py but I can't get an interactive test that links me to that. It's weirdly right there that we append to the workflow.configfiles AND run io.load_configfile that will trigger the bug to tell us it doesn't exist.  It's a catch 22 because self.configfiles is what generates the get_sources content, and it's the sources that exist.

What I've been able to figure out is that the interactive python setup that we have for testing, when running the "same thing" as the command line, does not result in any configfiles (and I've tested for each of kubernetes, tibanna, and just use-conda)

```
>>> workflow.configfiles
[]
```

It has to be related to the difference between the function and command line use right? But I just walked through the whole thing and I can't figure it out. Do you have any possible insights?  Something to try? A function to look at?

**Comment by vsoch** [comment]
I figured out the issue - and I was wrong about the differences in behavior (the error shows up for the command line but just later). The underlying issue came down to the generation of the archive name - I was using the self.workflow.basedir to derive a relative path (thinking this was the very base directory that has both of config and workflow in it) but in fact this is in reference to the "workflow" directory. What then happens is that the archive name is not properly generated, and the file not added (despite being present in the working directory). I didn't catch this with testing because I didn't have a config folder.

Here is an example of the basedir (the only I incorrectly thought to not include workflow)

```python
>>> self.workflow.basedir
'/home/vanessa/Documents/Dropbox/Code/Python/snakemake/snakemake-tutorials/dna-seq-varlociraptor/dna-seq-varlociraptor/workflow'
```

And thus when we generate an arcname for a file under the config folder, when we replace the basedir in the file path, it doesn't actually change:
```python
>>> arcname
'/home/vanessa/Documents/Dropbox/Code/Python/snakemake/snakemake-tutorials/dna-seq-varlociraptor/dna-seq-varlociraptor/config/config.yaml'
```
That file isn't added, and it's a silent error.

I'm testing both command line and interactive Python now, and I can no longer reproduce this issue - I'm going to close here and I'll update my branch in a bit! I've found another bug with the workflow, but it's not this one, which makes me pretty happy :)
