### ISSUE TITLE
--slurm option works when in srun but fails in sbatch

### ISSUE THREAD

**Issue by ccedmendoza** [snakemake/snakemake#2230]
**Snakemake version:** 7.25.0

**Describe the bug**

When runnig `snakemake --slurm` if I do so in a `srun` (for example `srun snakemake rule_a --slurm`) I have no issues. However, runnig the same command in a `sbatch` script will result in the following error:

```
srun: fatal: SLURM_MEM_PER_CPU, SLURM_MEM_PER_GPU, and SLURM_MEM_PER_NODE are mutually exclusive.
```

This is an issue because when running a very long pipeline I prefer using `sbatch`. It allows me to keep track of what the command used was and I don't need to keep the terminal alive. If I ran it using `srun` I would need to use `screen` or leave the computer on for it to have to finish.

**Minimal example**

Using the following single rule pipeline as an example:

```
# Snakefile
rule rule_a:
    output:
        "rule_a_output.txt"
    threads: 1
    shell:
        "echo 'some text' > {output}"
```

This way of running the pipeline will work:

```sh
srun snakemake rule_a --slurm -j 1
```

Using this sbatch file won't work:

```sh
#!/bin/bash
#SBATCH --job-name=test_snakemake
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

srun snakemake rule_a --slurm -j 1
```

Positionned in the same directory as the the Snakefile this won't work:

```sh
sbatch sbatch_file.sh
```

Complete log:

```
Job 0 has been submitted with SLURM jobid 3212151 (log: .snakemake/slurm_logs/rule_pouet/3212151.log).
[Mon Apr 24 17:39:34 2023]
Error in rule pouet:
    message: SLURM-job '3212151' failed, SLURM status is: 'FAILED'
    jobid: 0
    output: pouet_output.txt
    log: .snakemake/slurm_logs/rule_pouet/3212151.log (check log file(s) for error details)
    shell:
        echo 'pouet' > pouet_output.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-04-24T173851.613147.snakemake.log
```

Rule log:

```
Provided resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954
Select jobs to execute...
srun: fatal: SLURM_MEM_PER_CPU, SLURM_MEM_PER_GPU, and SLURM_MEM_PER_NODE are mutually exclusive.
[Mon Apr 24 17:38:57 2023]
Error in rule pouet:
    jobid: 0
    output: pouet_output.txt
    shell:
        echo 'pouet' > pouet_output.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by ccedmendoza** [comment]
Actually, I figured out the solution for this.

Adding the following directive to the sbatch script:

```sh
#SBATCH --mem=10G
```

I'm not sure why this fixed it but I would guess that requesting the memory explicitly will prevent snakemake from checking the `SLURM_MEM_PER_CPU`, `SLURM_MEM_PER_GPU`, and `SLURM_MEM_PER_NODE` environment variables.

**Comment by LLansing** [comment]
I'm running Snakemake 7.32.4 with the `--slurm` argument in order to submit jobs on a SLURM cluster (I rolled back from 8.x because it seems the `--slurm` option has been removed).
I painstakingly troubleshot this error message before discovering this issue page.
The bash script I submit to call the snakemake pipeline specified the memory request as `#SBATCH --mem-per-cpu=20000M` but my configuration was set the default memory request via `mem_mb=60000`. 
It would seem that using these two keywords ("mem-per-cpu", "mem_mb") was causing the issue. Given that the resources requested in the submitted bash script that calls `snakemake`  and the resources requested via config/workflow for rule-specific jobs are unrelated, this seems like a bug to me. 
The fix is somewhat unsatisfying, but it has got the pipeline running for me and submitting jobs.
