### ISSUE TITLE
Resume failed rules without wiping existing output files

### ISSUE THREAD

**Issue by tgelafr1** [snakemake/snakemake#2234]
**Is your feature request related to a problem? Please describe.**
There are numerous long running bioinformatic pipelines that  allow users to resume interrupted pipeline runs. Usually, these work by looking at existing files and not reproducing them if they already exist. This can save a lot of time if one step of a pipeline fails but many previous long running steps have succeeded. When running such a pipeline within a snakemake rule, I can save existing files by using `--keep-incomplete`. However, the ability to resume the rule meaningfully is lost because all the existing files are deleted before running the rule. This type of issue has led me to rerun the pipeline manually and circumvent the snakemake infrastructure.

**Describe the solution you'd like**
Allow a flag, like `--resume-incomplete` when running that allows the rule to run without deleting the output files before running. Like `--rerun-incomplete`, this would allow the rule to run even if it had been previously interrupted, but it would not remove existing files.

**Describe alternatives you've considered**
I haven't discovered a way to do this within the snakemake infrastructure (but if there is one, let me know!). The only workaround I've been able to use is to run the rule manually.

**Comment by tgelafr1** [comment]
This makes sense if you're writing your own code, it's scrappy, and you don't have built in checks yourself to check if files are complete or incomplete. But say I'm running (within a rule) a complex, proprietary pipeline provided by a third party that takes my fastq files for RNAseq and turns them into read counts. That code has been developed and tested to be robust to failures and allow re-execution with minimal redundancy. So it might execute step A and then fail at step B. However, the code is written such that it can verify that step A has been successfully completed and can be skipped. However, if snakemake wipes all the files from step A, it has to be run again no matter how smart the third party pipeline is. If step A took 3 days to run.... there's a lot of time lost.

The use case here is running _robust_ code where snakemake can trust the developer has more insight into the files produced. I think this should be difficult to do and take a lot of thought, but not impossible.

**Comment by SichongP** [comment]
> So it might execute step A and then fail at step B. However, the code is written such that it can verify that step A has been successfully completed and can be skipped. However, if snakemake wipes all the files from step A, it has to be run again no matter how smart the third party pipeline is.

Snakemake only deletes output files from failed steps, so step A should not be re-run.

**Comment by tgelafr1** [comment]
In my example, step A and step B are not rules defined in snakemake, but in the proprietary pipeline. Maybe some pseudocode would help.

here's my `Snakefile`:

```
rule rule_1:
    input: "raw.fastq"
    ouput: "filtered.fastq"
    run: ....

rule rule_2:
    input: "filtered.fastq"
    output: "gene_counts.txt"
    shell:
        "python3 big_third_party_pipeline.py -o {output} {input}"
```

here's `big_third_party_pipeline.py`:

```
def step_A():
    if os.isfile(intermediate_file):
        return intermediate_file
    else:
        <create intermediate file>
    return intermediate_file

def create_final_output(intermediate_file):
    <make `gene_counts.txt` based on intermediate_file>
    
 
if __name__ == "__main__":
    intermediate_file = step_A()
    create_final_output(intermediate_file)
```

Now say I trust `big_third_party_pipeline.py` to rerun gracefully, and I certainly am not going to change it because it's big and complicated. If rule_2 fails during `create_final_output` because e.g. I ran out of disk space, and I want to rerun it but use the output from `step_A` that already ran, I don't think snakemake will let me any which way. What I want is a way to tell snakemake "if `rule_2` fails, I trust it to rerun itself without you cleaning up after it. Let it!"

**Comment by SichongP** [comment]
In your example, when `rule_2` fails, the only file that will be removed (if it exists) is `gene_counts.txt`. Any intermediate files created by `big_third_party_pipeline.py` are not tracked by snakemake because they are not marked as `output` and therefore should be left alone. 

The only caveat is if `gene_counts.txt` is in its own sub-directory where no other rule writes output to, this directory might be deleted during cleanup, inadvertently removing all the intermediate files.

**Comment by troycomi** [comment]
I mostly agree with @SichongP, but I could see the utility of the enhancement.  Perhaps a better interface would be marking a file as being able to restart.  I can't think of a good name, but for clarity call it `restartable`.  Such output files shouldn't be deleted when the rule fails, but marked as needing to be rerun and not deleted when starting the rule.  For the example:
```
rule rule_1:
    input: "raw.fastq"
    ouput: "filtered.fastq"
    run: ....

rule rule_2:
    input: "filtered.fastq"
    output: restartable("gene_counts.txt")
    shell:
        "python3 big_third_party_pipeline.py -o {output} {input}"
```
So if `rule_1` fails the filtered fastq will get deleted, but `gene_counts` will stay around.  Then it's up to the workflow developer to determine if the flag is appropriate for each rule and handled properly.  And you'd probably need a CLI flag to disable it.

However, I would guess the majority of tools don't support restarting and having such a flag may end up causing more harm than good for people that aren't as familiar with the nuances of restarting a job.

As an alternative, you could get around snakemake with a param:
```
rule rule_2:
    input: "filtered.fastq"
    output: "gene_counts.txt"
    params:
        intermediate_output="gene_counts_tmp.txt"
    shell:
        "python3 big_third_party_pipeline.py -o {params.intermediate_output} {input} \n"
        "mv {params.intermediate_output} {output}
```
Snakemake doesn't know about the temp file, so it won't delete or handle it at all.  If the third party thing fails, snakemake knows the final output doesn't exist, but the temp file stays around.  On restart, the temp file is handed back to the tool and if it completes, the move command makes the final output.

Clearly the flag would be more clear, but since it's a minority usage I can see not wanting to pollute the syntax.

**Comment by tgelafr1** [comment]
Thanks @SichongP, good point. I think I got kind of turned around. Where I actually have this issue is indeed when I specify the _directory_ as an output, rather than a specific file. Then the whole directory is wiped, including intermediate files. An obvious workaround I should have seen is to give a specific file as the output, and then I think everything will work as I would like, although I'll lose the nice features around having a directory output, like it being auto-generated. And I can use the suggestion of @troycomi if I need to pass the directory to the rule of putting it in a parameter. I still think it might be a "nice to have" to allow a directory output to remain intact upon rerunning the rule for this reason, but it's definitely non-essential.

**Comment by troycomi** [comment]
Directory outputs should be reserved for cases when you don't know the output files, e.g. a checkpoint rule.  In cases where you know the outputs you should list them explicitly as it makes the workflow logic clearer and allows snakemake to monitor all outputs.

With regards to auto-generating directories, this happens normally:
```
rule test:
    output: 'a/long/path/out.txt'
    shell: 'echo hi > {output}'
```
Snakemake will create `a/long/path` before execution gets passed to the rule body.
