### ISSUE TITLE
Add "walltime" as an alias for the "runtime" resource

### ISSUE THREAD

**Issue by tdido** [snakemake/snakemake#2279]
Would there be place for a PR which added `walltime` as an alias for the `runtime` resource? We have a considerable amount of code that was developed for running with the [Slurm profile](https://github.com/Snakemake-Profiles/slurm) which happily accepts both, and we'd be facing a good deal of updating in order to have everything run with the new native executor.

**Comment by cmeesters** [comment]
Sorry for looking into this so late - since v8 the [executor code for SLURM lives in its own repo](https://github.com/snakemake/snakemake-executor-plugin-slurm/).

[`runtime` is a standard resource identifier in Snakemake](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#standard-resources). Introducing `walltime` as an alias for cluster users only, would mean a core change. I am reluctant to favour this change.

**Comment by tdido** [comment]
Thank you for getting back.

Yes. It was a bit of an unfortunate breaking change given the previous usage in profiles. We've since migrated all our pipelines to the new config, so this is no longer relevant (at least for us). Closing.
