### ISSUE TITLE
input-dependent resource specification fails

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#2555]
**Snakemake version**

`v8.0.1`

**Describe the bug**

Lambda functions to define resources (`runtime`, `mem` or `mem_mb`) are not supported. For example, this code works:
```
resources:
    runtime = lambda w: "2 h",
```

but this fails:
```
resources:
    runtime = lambda w, attempt: f"{2 * attempt} h",
```
and also this:
```
resources:
    runtime = lambda w, attempt, input: f"{2 * attempt * input.size_mb} h",
```

Might be related to #2510 and #2423.

**Logs**

```
WorkflowError:
Cannot parse mem or disk value into size in MB for setting mem_mb resource: <TBD>
```

**Comment by fgvieira** [comment]
Persists in `8.3.2`.

**Comment by fgvieira** [comment]
@christopher-schroeder I've been trying to fix this issue (since if not, I cannot update to `v8`), but I am not sure where the problem is (specially since it all worked fine in `v7`). I think that you might have fixed a similar issue back in `v7`; do you have any idea of where the issue might be?

thanks,

**Comment by cmeesters** [comment]
Hm, I believe the evaluation of resources is a bit screwed, might be related to the first part mentioned in PR 2627:

Putative function definitions in resource sections need to be evaluated. Subsequently, as snakemake potentially calls itself in executors, only a string ought to be set on the command line. We should dig into this. Alas, @johanneskoester and I might not find the time next week, although this issue is relevant to many (incl. myself).

**Comment by twrightsman** [comment]
@fgvieira Does #2690 fix this issue for you?

**Comment by fgvieira** [comment]
@twrightsman 

it definitely fixed the dryrun issue. thanks! :+1: 

Not sure if related (nor if it has any effect) but, when testing the latest version a bit further, saw that `mem_mib` is not being calculated correctly:
```
resources: mem_mb=21475, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=<TBD>, mem=20 GiB, runtime=30
```

In this case I have a remote input file and (I think because of a bug) `disk_mb = 1000`.
I define `mem=20 GiB` and this gets correctly converted to `mem_mb=21475`, but `mem_mib` gets `954`!
