### ISSUE TITLE
unrecognized arguments: --cluster

### ISSUE THREAD

**Issue by tiramisutes** [snakemake/snakemake#2615]
**Snakemake version**

V8.1.0
**Describe the bug**

The snakemake installed by Conda cannot submit tasks to the cluster for running using the `--cluster` parameter.
**Logs**

**Minimal example**

`snakemake  -j 1000 -s workflow/Snakefile  --use-conda --cluster-config config/cluster.json --cluster "bsub -q normal -o {cluster.output} -e {cluster.error} -n {threads}"`
**Additional context**

**Comment by yichechang** [comment]
There are major chances made since v8. See [migration guide](https://snakemake.readthedocs.io/en/stable/getting_started/migration.html). Specifically, the table from that page include how `--cluster` in < v8 should now be changed to `--executor <some params>` for >= v8.0. v8 also introduced the plugin system so you'll have to install certain executor plugin separately. I haven't updated to v8, so take above with a grain of salt. 

If you'd just like to use something developed for snakemake < v8 without changing how you run the workflow, I think limiting your snakemake version to <8.0 should work.

**Comment by tiramisutes** [comment]
May I ask how to specify the cluster configuration file? No substitute parameters for `--cluster-config` after v8.0 were found in [migration guide](https://snakemake.readthedocs.io/en/stable/getting_started/migration.html).

**Comment by yichechang** [comment]
Sorry, can't be more helpful. I personally haven't been able to learn about the new system.

For usage questions I think you might get more help on stackoverflow. You could also check if someone has asked about similar questions: https://stackoverflow.com/questions/tagged/snakemake

**Comment by nataquinones** [comment]
> May I ask how to specify the cluster configuration file? No substitute parameters for `--cluster-config` after v8.0 were found in [migration guide](https://snakemake.readthedocs.io/en/stable/getting_started/migration.html). In addition, the snakemake document ([Cluster execution](https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#cluster-execution)) needs to be updated.

This would be much appreciated. The migration document doesn't seem informative enough to make the transition smooth.

**Comment by freekvh** [comment]
For the people, like me, that end up here searching for solutions after dusting off old Snakemake pipelines, I think this it what you are looking for: https://snakemake.readthedocs.io/en/stable/getting_started/migration.html#id6

Cluster configuration is not supported anymore it says here: https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-not-supported-anymore (there is a link to more info on Profiles but that is a circular link). I found this information regarding Profiles: https://github.com/snakemake-profiles/doc
