### ISSUE TITLE
Errors to stdout or to stderr?

### ISSUE THREAD

**Issue by rhpvorderman** [snakemake/snakemake#2757]
Back when I started [pytest-workflow](https://github.com/lumc/pytest-workflow) in the beginning of 2019, I added some integration tests to ensure snakemake workflows could be always properly tested. Back then, snakemake reported errors to stdout. 

In October 2021 I had to make  a change to the testing, because snakemake switched to reporting errors on stderr. See https://github.com/LUMC/pytest-workflow/commit/51e9c1227b6a368d92c30896dacb4affb34d91fc. 

Then in February 2022, this had to be switched to stdout again. https://github.com/LUMC/pytest-workflow/commit/e24d9d0a093bebbbe74cbe6fa5cc0eed9cde6832

And now in march 2024, apparently something has changed **again**, and errors are reported on stderrr. https://github.com/LUMC/pytest-workflow/commit/ae51d3b759bcd71418b54e071513f11a116b14a1 . 

This is slightly inconvenient, and I wouldn't have made an issue. But then I saw this issue on the cutadapt issue tracker: https://github.com/marcelm/cutadapt/issues/767, which complains that cutadapt is not writing errors to stderr and that this is a hindrance to snakemake.

Does this mean snakemake is from now on always going to report errors to stderr as well?

**Comment by johanneskoester** [comment]
Mhm, to be honest, this never intentionally changed. Snakemake has always been reporting its own errors to stderr, as well as its logging. Only in case of dryrun, snakemake logs to stdout so that you can pipe it easily into less. If there was any switch in that behavior, it was unintentional and I apologize.
The recent issue in cutadapt is unrelated to this. Cutadapt just mixed QC output (STDOUT) and errors and that was invonvenient for the snakemake-wrapper for cutadapt and also felt unintuitive to me. Hence the request.
In general it is up to the individual rule that invokes a tool to properly redirect errors and logging into log file(s) specified by the log directive in the rule. Snakemake itself does not really care, but good workflows should have a log file for each rule that ends up with any errors and logging that occurred during the execution of that rule.

**Comment by rhpvorderman** [comment]
Thanks you for the clarification. I was never aware that dry-run errors where always supposed to be on stdout. I thought the switch to stderr was intentional.  

I agree that the cutadapt issue is unrelated. It is just the thing that triggered me to file this issue. I shouldn't have brought it up. My apologies for that.

So if I understand correctly, the functional testing that I run that now has errors on *stderr* is technically wrong because dry-wrong should output to stdout? Which it is not doing in this case, so there is a bug in snakemake that I should report?

**Comment by johanneskoester** [comment]
Yes, in case of dryrun, it should be stdout. I just checked it, the problem was introduced with Snakemake 8. Fix is in PR https://github.com/snakemake/snakemake/pull/2759

**Comment by rhpvorderman** [comment]
Thanks!
