### ISSUE TITLE
Moving workflow to version 8 gives `IndentationError´ on Windows. 

### ISSUE THREAD

**Issue by melund** [snakemake/snakemake#2765]
**Snakemake version**
8.9.0

**Describe the bug**
I am migrating a workflow from version 6 but I ran into a bug which gives me an `IndentationError` in version 8. 

I am on Windows, and I suspect that this is a `crlf`/`lf` problem since I can "fix" the issue if force the Snakefile to use `lf` instead of `crlf`. But it just moves the bug to some of my other workflow files.

Why does snakemake 8 expect the my files to use `lf`? Python is usually not fuzzy, and loads files with universal newlines. 

Here is the code which cause issues and the traceback. 

![image](https://github.com/snakemake/snakemake/assets/1038978/947aebb2-1c4a-4c6f-8337-7094cd5c3eaa)

```
  File "D:\AnyBodyModels\Agada-processing\.pixi\envs\default\Lib\site-packages\snakemake\workflow.py", line 1398, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AnyBodyModels\Agada-processing\workflow\Snakefile", line 44
    PATIENT_IDS.append(p)
IndentationError: expected an indented block after 'for' statement on line 43

IndentationError in file D:\AnyBodyModels\Agada-processing\workflow\Snakefile, line 42:
expected an indented block after 'for' statement on line 43:
        PATIENT_IDS.append(p)
        
```

**Comment by aforestsomewhere** [comment]
Hi Morten, I think I am seeing similiar behaviour migrating from an older Snakemake version to 8.10.

`def get_genome_size(wildcards):
    sizes=config['genome_sizes'].get(wildcards.sample, None)
    return sizes`

results in:

`IndentationError in file run_subsampling.py, line 16:
expected an indented block after function definition on line 15:
    sizes=config['genome_sizes'].get(wildcards.sample, None)
`
I've checked and the file doesn't seem to have any CRLF in it

**Comment by melund** [comment]
@meg256 / @aforestsomewhere Are you both on Windows, or what platform are you using?

**Comment by ethan-shanahan** [comment]
Hello,
I have also encountered this issue. I am using Windows 11, Python 3.12.3, and tested a few version of Snakemake. I received an IndentationError when using a for loop on Snakemake versions 8.4.12 and 8.10.7. Version 8.4.7 however did not raise this error.

The error isn't raised on any of these versions if I enforce the "LF" end of line sequence on the Snakefile, rather than "CRLF".

Here is the Snakefile I used to test this bug:
```python
rule all:
    input: "testfile.txt"

for i in range(1):
    rule test:
        input: "existingfile.txt"
        output: "testfile.txt"
        shell: f"echo test{i} > {{output}}"
```

And here is the error message:
`IndentationError in file C:\...\Snakefile, line 5:`
`expected an indented block after 'for' statement on line 11 (Snakefile, line 5)`

**Comment by aforestsomewhere** [comment]
> @meg256 / @aforestsomewhere Are you both on Windows, or what platform are you using?

Centos HPC for Snakemake itself, but it is true that I am editing code in VSCode on Windows occasionally

**Comment by aforestsomewhere** [comment]
> enforce the "LF" end of line sequence on the Snakefile

Is there a more modular/elegant way to do this than running a helper script to replace \r\n to \n? I feel like there probably is...

**Comment by ethan-shanahan** [comment]
I also use VS Code; there you can simply specify the line ending per file in the status bar. If you use git, I believe there is an automated conversion possible there too. These tricks should help circumvent the issue temporarily.

As for the issue at hand, I don't recall reading anywhere in the docs that the "LF" end of line sequence is required since ~8.4.7. Maybe I missed it, but if not there may be a bug here.

**Comment by melund** [comment]
This is very confusing bug. I can't recreate it when I `pip install` snakemake from source. That just works, also on the newest versions. It makes debugging a bit harder.

It only happens when I use the `bioconda` conda packages. It also seems important that I remove the conda environments completely between my test of this issue. Otherwise, it may appear to work but then fail the next time I create a new environment. 

I tried old versions all the way back to snakemake 6. For me the problem started to appear in 6.4, while working in 6.3. That is with @ethan-shanahan's example.

I couldn't see anything in the changelog for 6.4 that should cause this behavior. I also think I have been running with newer versions that 6.4, where I haven't seen this issue. But maybe I was just simply running on the same environment.

**Comment by ethan-shanahan** [comment]
Confusing is right.
I have been installing from bioconda so far. I tried narrowing down the problem version myself and ended up on version 8.4.11 where the error first occurs. However, there doesn't appear to be any 8.4.10 version on bioconda. Rather, it jumps from 8.4.9 and then there are two 8.4.11 versions. Possibly just a mislabeling but an odd coincidence. I checked the changelog and there is definitely nothing concerning in 8.4.11, but I can't say anything about 8.4.10. I haven't been able to try version 6 on my system unfortunately.

I then used pip to install snakemake 8.10.7 and I could also not reproduce the bug in this environment.

I'm not sure what @melund means by removing conda environments and the illusion of the bug disappearing. I have been creating new environments for each version of snakemake and the issue is reliably present.

**Comment by melund** [comment]
Ok. I think I have nailed the problem 🥳 

It was caused by the `smart_open` dependency. Between 6.3 and 6.4, snakemake started to depend on smart-open. `smart-open` had a bug where it would not open files correctly if supplied with a `Path` variable instead of a string. I just found that bug while debugging. But it turns out that the bug was fixed in smart-open 4.

Unfortunately, "smart-open" was [pinned to version 3](https://github.com/bioconda/bioconda-recipes/blob/2448739fda6826d72212aea604d4592b75afb1a4/recipes/snakemake/meta.yaml#L105) in the conda-build recipe. That pin was never removed even as it was lifted in [`setup.cfg`](https://github.com/snakemake/snakemake/blob/84658188e0ad6104ba49bc2441b179c2c2cc021c/setup.cfg#L53C1-L54C1)

This means that the bug was only seen when using the bioconda packages.

I have made a PR to the conda-recipe to fix the issue: 
https://github.com/melund/bioconda-recipes/pull/1

@johanneskoester, can you merge the PR on the bio-conda recipe?

**Comment by melund** [comment]
Johannes have fixed the restriction on smart-open in the conda packages for 8.10.8. 
https://github.com/bioconda/bioconda-recipes/pull/47340

You may still need to force an update on smart-open. So I will probably try to make a PR to require "smart-open>=4". Otherwise, people may still encounter this bug.

**Comment by melund** [comment]
This issue is now fixed.
