### ISSUE TITLE
software deployment conda confusion

### ISSUE THREAD

**Issue by pdimens** [snakemake/snakemake#2807]
**Snakemake version**
8.10.7 (snakemake-minimal)

**Describe the bug**

The `--help` string for snakemake lists the new `--software-deployment-method` option, however in the section immediately following it, `--use-conda` is listed and says the default is false. These options are confusing-- does one need to use both
`--software-deployement-method conda` **and** `--use-conda`, or would it be enough to just use the --sdm?

**Logs**

**Minimal example**

**Additional context**

**Comment by gernophil** [comment]
I am still confused: The [Snakemake docs](https://snakemake.readthedocs.io/en/stable/executing/cli.html#snakemake.cli-get_argument_parser-conda) say:
> `--use-conda`
>     If defined in the rule, run job in a conda environment. If this flag is not set, the conda directive is ignored.
>     Default: `False`

So, if I use `--sdm conda` instead of `--use-conda`, will the yaml file for the environment be ignored? Also, is `--conda-frontend` usable with `--sdm conda` or only with `--use-conda`? I think the docs need some clarification on that.

**Comment by mschilli87** [comment]
Also see [this question on Stackoverflow](https://stackoverflow.com/questions/79503285).
Maybe it will take less than a year to get a straight answer there. 😉

**Comment by mschilli87** [comment]
@pdimens: Thanks for sharing your findings. Do you have any source?
Maybe somebody could draft a pull request to update the documentation. Clearly, this question keeps coming up and several people struggled to find an answer.
