### ISSUE TITLE
bash external script: is it possibile to use it

### ISSUE THREAD

**Issue by aborruso** [snakemake/snakemake#294]
Hi,
I think it's not possible, but it would be great to use something like `echo ${input[1]}` in an external bash script.

Thank you for this great tool

**Comment by aborruso** [comment]
I must use mailing list, I'm closing it

**Comment by bricoletc** [comment]
Hi @aborruso , what came out of this? I'm quite keen on this feature too!

**Comment by aborruso** [comment]
hi @bricoletc this is for you https://groups.google.com/d/msg/snakemake/Nv9tzlgeqNE/KzoZro1yBQAJ

**Comment by bricoletc** [comment]
Thanks for your reply @aborruso !

I'm a little confused by that answer. Have you successfully called bash scripts from `script` directive inside a `rule`?

Here's what I get when running the following snakefile:

```
rule mkfiles:
	params:
		pref="test"
	script:
		"mkfiles.sh"
```

where the bash script contains:

```
for i in $(seq 1 5); do
	echo {snakemake.params.pref}$i
done
```

Stderr:
```RuleException:
ValueError in line 5 of /path/to/tests/Snakefile:

Unsupported script: Expecting either Python (.py), R (.R), RMarkdown (.Rmd) or Julia (.jl) script.
  File "/path/to/tests/Snakefile", line 5, in __rule_mkfiles
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```

**Comment by aborruso** [comment]
I have not tested, I'm sorry.

Please write a reply in the mailing list

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il gio 16 apr 2020, 20:37 Brice Letcher <notifications@github.com> ha
scritto:

**Comment by bricoletc** [comment]
I think this is worth re-examining then.

Is lack of support for shell script because it is hard to implement, or for design reasons?

**Comment by mbhall88** [comment]
I think this is doable.

Since Bash v4, there are [associative arrays](https://tldp.org/LDP/abs/html/declareref.html), which are analogous to python dictionaries. There is a nice tutorial [here](https://www.xmodulo.com/key-value-dictionary-bash.html) showing how to work with these.

The main task for getting this working I expect is converting a python dictionary to a bash dictionary. I couldn't find any (obvious) existing libraries for this, but we could easily write a sublibrary within snakemake to do this conversion and then inject it into the bash script.

I'd be happy to dig into this once #1053 is merged (and provided @johanneskoester is happy to include such a feature).
