### ISSUE TITLE
All rules executing as local rules

### ISSUE THREAD

**Issue by karltayeb** [snakemake/snakemake#2947]
v8.14.0

It seems that all rules are being marked as localrules, even though I never use the localrule or localrules directives.

```
# Snakefile
rule test_rule:
    output: 'test.txt'
    shell: "touch {output}"
```

When I call `snakemake -c1 test.txt` I get

```
Fri Jul  5 14:30:10 2024]
localrule test_rule:
    output: test.txt
    jobid: 0
    reason: Missing output files: test.txt
    resources: tmpdir=/home/ktayeb

[Fri Jul  5 14:30:10 2024]
Finished job 0.
1 of 1 steps (100%) done
```

This is troubling because when I try to execute jobs using my cluster's resources, all the rules are run on the local node instead of being farmed out to jobs as expected. I even tried explicity declaring the rule as not local by

```
# Snakefile
rule test_rule:
    output: 'test.txt'
    localrule: False
    shell: "touch {output}"
```
Which didn't change anything. Am I missing something?

**Comment by cademirch** [comment]
What command did you use to execute on the cluster resources?

**Comment by cmeesters** [comment]
And which is your Snakemake software stack (plugins and versions)?

**Comment by karltayeb** [comment]
I was using the cluster-generic plugin and the simple profile template here https://github.com/jdblischak/smk-simple-slurm/blob/main/simple/config.v8%2B.yaml,

However, I don't think it matters-- the rule is indicated as a `localrule` whether I call it with cluster resources, or just executing locally. It seems that all rules are being marked as local by default and I don't know how to change that behavior.

**Comment by cmeesters** [comment]
Please have a look at the [snakemake-executor-plugin-slurm](github.com/snakemake/snakemake-executor-plugin-slurm/). You will find the documentation [here](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html). 

Since Snakemake v7.something SLURM is natively supported. Since v8 we shifted to various [plugins](https://snakemake.github.io/snakemake-plugin-catalog/), to ease maintenance.

**Comment by cmeesters** [comment]
@AmelZulji please check: is it really executed twice or mentioned twice in the log? 

Just check

```Python
rule all:
     input: "results/a.out"

rule test1:
     output: "results/a.out"
     shell: "echo $SLURM_JOB_ID >> {output}"
```

Note: This is a) not the same issue as described by @karltayeb and b) not an issue at all. It is an artifact of the implementation and merits better documentation.

**Comment by AmelZulji** [comment]
Thank you, @cmeesters. I can confirm that it is just reported twice as you mentioned.

**Comment by dportik** [comment]
Hi @cmeesters,
I believe I am getting the same error reported above as @karltayeb, and it looks like my rules are being regarded as local rules even though they aren't specified as such in my snakemake file.

I installed snakemake 8.25 via conda using the following:
`conda create --name meta_snake -c conda-forge -c bioconda snakemake=8.25 snakemake-executor-plugin-cluster-generic`

I am running snakemake from our HPC system, from an interactive session running with 8 threads.
(e.g., `srun --partition compute9 --job-name="interactive" --cpus-per-task=8 --ntasks=1 --nodes=1 --export=HOME,TERM,NONE --pty /bin/bash -l`)

I ran this snakemake command:
```
snakemake --snakefile Snakefile-runHifiasm.smk \
--configfile configs/Sample-Config-Fermented-test.yaml \
--software-deployment-method conda \
--executor cluster-generic \
--cluster-generic-submit-cmd "mkdir -p HPC_logs/{rule} && sbatch --partition=compute9 --nodes=1 --cpus-per-task={threads} --output=HPC_logs/{rule}/{jobid}.{wildcards}.txt" \
-j 30 \
--jobname "{rule}.{wildcards}.{jobid}" \
--latency-wait 60 
```
I know it's clunky but I am trying to reproduce the call for the same workflow that was run successfully using snakemake 5.26 (where `--cluster` was supported). Happy to take any pointers on simplifying this, but that's a side topic.

Anyways here is what appears next:
```
Config file config.yaml is extended by additional config specified via the command line.
host: mp2005
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided remote nodes: 30
Job stats:
job               count
--------------  -------
Cleanup               2
Gfa2Fasta             2
RunHifiasmMeta        2
all                   1
total                 7

Select jobs to execute...
Execute 2 jobs...

[Wed Dec 11 15:55:40 2024]
rule RunHifiasmMeta:
    input: inputs/ffPac_15.fastq.gz
    output: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_15.completed.txt
    log: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/logs/ffPac_15.RunHifiasmMeta.log
    jobid: 1
    benchmark: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/benchmarks/ffPac_15.RunHifiasmMeta.tsv
    reason: Missing output files: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_15.completed.txt
    wildcards: sample=ffPac_15
    threads: 8
    resources: tmpdir=<TBD>

Submitted job 1 with external jobid 'Submitted batch job 45038031'.

[Wed Dec 11 15:55:41 2024]
rule RunHifiasmMeta:
    input: inputs/ffPac_03.fastq.gz
    output: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_03.completed.txt
    log: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/logs/ffPac_03.RunHifiasmMeta.log
    jobid: 2
    benchmark: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/benchmarks/ffPac_03.RunHifiasmMeta.tsv
    reason: Missing output files: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_03.completed.txt
    wildcards: sample=ffPac_03
    threads: 8
    resources: tmpdir=<TBD>

Submitted job 2 with external jobid 'Submitted batch job 45038032'.
```

Both jobs should be receiving 48 threads, as specified in the config.yaml and the snakemake workflow thread argument (`config.yaml`, `Snakefile-runHifiasm.smk`, & `Sample-Config-Fermented-test.yaml` attached below). But they are showing 8 threads here.

Looking at the HPC_log for one of the samples, I find:
```
Config file config.yaml is extended by additional config specified via the command line.
host: mp2003
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Select jobs to execute...
Execute 1 jobs...

[Wed Dec 11 15:56:06 2024]
localrule RunHifiasmMeta:
    input: inputs/ffPac_15.fastq.gz
    output: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_15.completed.txt
    log: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/logs/ffPac_15.RunHifiasmMeta.log
    jobid: 0
    benchmark: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/benchmarks/ffPac_15.RunHifiasmMeta.tsv
    reason: Forced execution
    wildcards: sample=ffPac_15
    threads: 8
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/tmp

[Wed Dec 11 15:58:00 2024]
Finished job 0.
1 of 1 steps (100%) done
Storing output in storage.
```

And for the other sample, this was in the HPC_log: 
```
Config file config.yaml is extended by additional config specified via the command line.
host: mp2001
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Select jobs to execute...
Execute 1 jobs...

[Wed Dec 11 15:56:06 2024]
localrule RunHifiasmMeta:
    input: inputs/ffPac_03.fastq.gz
    output: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/1-progress/ffPac_03.completed.txt
    log: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/logs/ffPac_03.RunHifiasmMeta.log
    jobid: 0
    benchmark: /dept/appslab/projects/old/2024/dp_snake-Run-hifiasm/benchmarks/ffPac_03.RunHifiasmMeta.tsv
    reason: Forced execution
    wildcards: sample=ffPac_03
    threads: 8
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/tmp

[Wed Dec 11 15:56:40 2024]
Finished job 0.
1 of 1 steps (100%) done
Storing output in storage.
```

This is confusing because it shows the host names are different from one another, and different from my interactive location. But it looks like it was assigned as a local rule, and somehow scaled down to run with 8 threads. 

Any idea what's going on here? Am I missing something obvious?

Any help would be greatly appreciated!


[Config-Sample-snakemake.zip](https://github.com/user-attachments/files/18103767/Config-Sample-snakemake.zip)
