### ISSUE TITLE
`run` directive will reinitialize the global variables

### ISSUE THREAD

**Issue by jiangyun-fun** [snakemake/snakemake#3130]
**Snakemake version**

```bash
❯ snk --version
8.20.6
```

**Describe the bug**

**Wrong behavior:**
```py
from datetime import datetime
NOW = datetime.now().strftime("%Y%m%d-%H%M%S-%f")

print(NOW)
rule test:
    output:
        NOW
    run:
        print(NOW)
        shell(
            "touch {output}",
        )
```

Above script will raise error:

```
❯ snakemake
20241011-105243-080949
Assuming unrestricted shared filesystem usage.
host: xxx
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
test         1
total        1

Select jobs to execute...
Execute 1 jobs...

[Fri Oct 11 10:52:43 2024]
localrule test:
    output: 20241011-105243-080949
    jobid: 0
    reason: Missing output files: 20241011-105243-080949
    resources: tmpdir=/tmp

20241011-105243-347781
host: xxx
20241011-105243-347781
Waiting at most 5 seconds for missing files.
MissingOutputException in rule test in file /path/to/Snakefile, line 5:
Job 0 completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
20241011-105243-080949 (missing locally, parent dir not present)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-11T105243.081409.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Expected behavior:**
If I use `shell`/`script` directive like below, it works fine:

```py
from datetime import datetime
NOW = datetime.now().strftime("%Y%m%d-%H%M%S-%f")

print(NOW)
rule test:
    output:
        NOW
    shell:
        """
echo {output}
touch {output}
        """
    # script:
    #     "test.py"
```
test.py:
```py
from pathlib import Path

file = Path(snakemake.output[0])

file.touch()
```

**Additional context**

It seems that with `run` directive, `NOW = datetime.now().strftime("%Y%m%d-%H%M%S-%f")` will run twice, which may cause unexpected behaviors. Is it better to let `run` directive works like `script` directive?

**Comment by jjjermiah** [comment]
From a basic understanding of the codebase, I think this is fundamentally due to how the `run` directive "spawns" a subprocess:

https://github.com/snakemake/snakemake/blob/1874fa86b1ebf52ece6646f32d4a3ed025499183/snakemake/executors/local.py#L175-L187 

Which from my understanding runs a subprocess call to snakemake again with just that rule as allowed. You can see the `spawned job: ...` log if you add `--verbose` to your cmdline args. 

Since this subprocess is another snakemake run, it recomputes the `NOW` in the subprocess. 

I'm not sure why the subprocess route is implemented for the `run` directive, but adding `--force-use-threads` bypasses this (though I'm not sure if that is the intended use case of the argument)
