### ISSUE TITLE
rust-script >= 0.23.0 fails with current version of snakemake

### ISSUE THREAD

**Issue by jackerschott** [snakemake/snakemake#3183]
**Snakemake version**
8.25.1

**Describe the bug**
rust-script>=0.23.0 fails with the current version of snakemake since snakemake provides an outdated command line.

**Logs**

**Minimal example**
Use rust-script with a version >= 0.23.0, with a snakefile
```
workflow/Snakefile
---
rule all:
    input:
        "bla.txt"

rule bla:
    output:
        "bla.txt"
    script:
        "scripts/bla.rs"
```
and a rust script
```
workflow/scripts/bla.rs
---
std::fs::File::create(&snakemake.output[0]).unwrap();
```
The snakemake execution will fail with either `the argument '--dep <dep>' cannot be used multiple times` or `unexpected argument '--features' found`.

**Comment by mbhall88** [comment]
Thanks for reporting this @jackerschott. The issue seems to be that the conda-forge package for rust-script is stuck on v0.22.0, hence why this didn't get flagged by failing tests (as the tests use v0.22.0).

I'll try and get the [conda-forge package](https://github.com/conda-forge/rust-script-feedstock) updated so we can get a fix in for this

**Comment by FelixMoelder** [comment]
It seems like the issue still exists even after updating the conda package to `0.35`. Probably there has been some change after `v0.22` causing some incompatibility issue.
