### ISSUE TITLE
.Rprofile ignored when running an R script

### ISSUE THREAD

**Issue by JulioV** [snakemake/snakemake#54]
**Snakemake version**
5.7.1

**Describe the bug**
A rule executing an R script using the `script` directive does not execute the content of .Rprofile. I found out this was the case because my packrat environment is not being loaded (the line `source("packrat/init.R"` is inside .Rprofile)

**Logs**
If applicable, any terminal output to help explain your problem.

**Minimal example**
Configure a packrat folder
 - `R -e 'install.packages(\"packrat\", repos=\"http://cran.us.r-project.org\")'`
 - `R -e 'packrat::init()'`

Install RMySQL
 - R -e 'install.packages(c("RMySQL"))'

Create a rule executing an R file with only one line:
- library(RMySQL)

**Additional context**
.Rprofile, packrat folder and the snakefile are in the root directory

**Comment by JulioV** [comment]
I found out that it was a consequence of [this fix](https://bitbucket.org/snakemake/snakemake/issues/970/ignore-r-profile-when-executing-r-scripts). I agree with the last comments, this breaks packrat and the alternative of loading the .Rprofile on every new script seems a bit cumbersome.

Is there a flag (can we add one if it doesn't exist) to load a .Rprofile for all scripts?

**Comment by johanneskoester** [comment]
I think it is indeed best to explicitly load .Rprofile in the script if it needs it. This way, the reader immediately sees the dependency instead of having to know about such internals. The downsides of loading .Rprofile and thereby accidentally including user specific context is just too large. Also, having a global flag would not help, because workflow results should not depend on command line flags given. This would hamper reproducibility.

**Comment by deto** [comment]
Probably not the best place to ask, but I had a question regarding this.

Say a colleague has R installed with all the requisite third-party libraries, but they have them in a user-library (which normally gets loaded via ~/.Rprofile).

How can they download an run a workflow I've made in Snakemake?  I don't want to specify *my* paths in the .R files as that won't make the workflow portable.  I feel like I'm missing the expected workflow here - can someone clarify?

**Comment by karldw** [comment]
@deto, just another user here, but you can achieve this by setting the `R_LIBS_USER` environment variable before running Snakemake (but see #490)

**Comment by kalenkovich** [comment]
> I think it is indeed best to explicitly load .Rprofile in the script if it needs it. This way, the reader immediately sees the dependency instead of having to know about such internals. The downsides of loading .Rprofile and thereby accidentally including user specific context is just too large. Also, having a global flag would not help, because workflow results should not depend on command line flags given. This would hamper reproducibility.

The problem with loading `.Rprofile` in every script is that it is easy to forget to do so. That is not a problem, of course, when it causes an error. But sometimes the script will run but produce unexpected results due to the package version differences.

Could maybe the renv environment be specified similarly to the way conda environments are?
