### ISSUE TITLE
touch files not working with Kubernetes

### ISSUE THREAD

**Issue by gdeoli** [snakemake/snakemake#596]
**Snakemake version**
5.22.1

**Describe the bug**
When flagging an output with touch(), in a given rule, the file isn't created, when the workflow is executed in the cloud. 

**Logs**
MissingOutputException in line 10 of /workdir/Snakefile:
Job completed successfully, but some output files are missing. Missing files after 5 seconds:
[\<bucket\>/sub-folder]/fileJob2.txt
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
  File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 544, in handle_job_success
  File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 225, in handle_job_success

**Minimal example**

_Snakefile_
rule all:
        input:
                "fileJob2.txt"

rule job1:
	output: "fileJob1"
	shell: "echo Hello World -- job1 > {output}"

rule job2:
        input: "fileJob1"
        output: touch("fileJob2.txt")
        shell: "echo Hello World! -- job2"

_Cmd_
`snakemake --kubernetes --default-remote-provider=S3 --default-remote-prefix=<bucket>/sub-folder --envvars AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY`

**Additional context**
The workflow runs fine in my machine, and also if deployed with tibanna. However, when I attempt to run it using kubernetes, it does not create fileJob2.txt. Rule Job1 runs ok and the file is created at the required bucket. I have even increased latency-wait to 20s, (just to give it a try), but no success. The AWS cluster was built with 3 nodes, running t3.micro EC2 instances using eksctl.

**Comment by dcroote** [comment]
I can confirm this also occurs in version 5.26.1 with Kubernetes on Google Cloud.

@vsoch - do you happen to know if `touch()` works with the GLS backend?

Potentially related: #583

**Comment by vsoch** [comment]
@dcroote I haven’t seen it (yet) - are you able to enable the API and run with the GLS executor to quickly test?

**Comment by dcroote** [comment]
Sure, I'll give it a try

**Comment by dcroote** [comment]
@vsoch - looks like the same `MissingOutputException` on GLS:

```bash
  - containerStopped:
      actionId: 1
      exitStatus: 1
      stderr: |
        utput: sm-test-gs/fileJob2.txt
            jobid: 0
            resources: mem_mb=1000, disk_mb=12000

        Downloading from remote: sm-test-gs/fileJob1
        Finished download.
        Waiting at most 0 seconds for missing files.
        MissingOutputException in line 9 of /workdir/Snakefile:
        Job completed successfully, but some output files are missing. Missing files after 0 seconds:
        sm-test-gs/fileJob2.txt
```

**Comment by vsoch** [comment]
It must be a shared issue with touch then - we’ve definitely had issues with the remote prefix in other areas. Unless you beat me to it, I’ll take a look this week.

**Comment by dcroote** [comment]
Makes sense.  I'm guessing `touch()` works on Tibanna as its executor explicitly handles `--default-remote-prefix`:

https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/executors/__init__.py#L1923-L1933

**Comment by vsoch** [comment]
Just about to go to bed, but I wanted to reproduce the issue so I'd have a good place to start tomorow. Here is the command to reproduce with GLS:

```bash
snakemake --default-remote-prefix snakemake-testing/touch --google-lifesciences --default-resources "machine_type=n1" --container-image snakemake/snakemake:v5.26.1
```
and the same Snakefile
```
rule all:
    input: "fileJob2.txt"

rule job1:
    output: "fileJob1"
    shell: "echo Hello World -- job1 > {output}"

rule job2:
    input: "fileJob1"
    output: touch("fileJob2.txt")
    shell: "echo Hello World! -- job2"
```
Reproduced

```

        Downloading from remote: snakemake-testing/touch/fileJob1
        Finished download.
        Waiting at most 0 seconds for missing files.
        MissingOutputException in line 8 of /workdir/Snakefile:
        Job completed successfully, but some output files are missing. Missing files after 0 seconds:
        snakemake-testing/touch/fileJob2.txt
        This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
          File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 566, in handle_job_success
          File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 243, in handle_job_success
        Removing output files of failed job job2 since they might be corrupted:
        snakemake-testing/touch/fileJob1
        Shutting down, this might take some time.
        Exiting because a job execution failed. Look above for error message
        Complete log: /workdir/.snakemake/log/2020-10-05T044829.738154.snakemake.log
```
I'll test interactively to see if we can do something similar for GLS. But better, if it's a shared issue between K8 and GLS, it would be nice to not have to roll a custom implementation any time a new executor is added. Anyhoo, more tomorrow!

**Comment by vsoch** [comment]
Okay, interactive debugging! First, let's inspect the job.input values at (mostly) the same spot for the GLS executor - the run() function. For the step that will fail, running on the local machine the values for the input and output prefix is correct (I chose snakemake-testing/touch)

```python
job.input
['snakemake-testing/touch/fileJob1']

job.output
['snakemake-testing/touch/fileJob2.txt']
```

But what is confusing me is the strategy that tibanna takes - it seems to remove the remote prefix for the VM and have the paths be relative, as if the prefix doesn't exist. I don't think this is how it works on GLS, which would create that nesting of filepaths on the instance. What Tibanna must do is copy the files without the prefix, relative, and then restore the s3 storage prefix at the end. But I wanted to test this to be absolutely sure, so I brought up an instance manually, installed Snakemake the same as the [Dockerfile](https://github.com/snakemake/snakemake/blob/master/Dockerfile) and then issued the same commands that the worker would. This is slightly adjusted for different permissions shelling into the instance:

```bash
sudo mkdir /workdir
sudo chown -R vanessa /workdir
cd /workdir
wget -O download.py https://gist.githubusercontent.com/vsoch/f5a6a6d1894be1e67aa4156c5b40c8e9/raw/a4e9ddbeba20996ca62745fcd4d9ecd7bfa3b311/gls.py
chmod +x download.py 
source activate snakemake || true
python download.py download snakemake-testing source/cache/workdir-294c473ccde16867a8ca416bccaa3087cbef159e365716393fcf7cd637417030.tar.gz /tmp/workdir.tar.gz 
tar -xzvf /tmp/workdir.tar.gz
```
That extracts the working directory on my local machine so it's pretty much the same. Now we run the first (working) snakemake command to handle the generation of the first file.

```bash
$ snakemake snakemake-testing/touch/fileJob1 --snakefile Snakefile --force -j --keep-target-files --keep-remote --latency-wait 0 --scheduler greedy --attempt 1 --force-use-threads --max-inventory-time 0  --allowed-rules job1 --nocolor --notemp --no-hooks --nolock  --default-remote-provider GS --default-remote-prefix snakemake-testing/touch  --default-resources "mem_mb=15360" "disk_mb=512000"
Building DAG of jobs...

Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	job1
	1

[Mon Oct  5 17:06:18 2020]
rule job1:
    output: snakemake-testing/touch/fileJob1
    jobid: 0
    resources: mem_mb=15360, disk_mb=512000

Uploading to remote: snakemake-testing/touch/fileJob1
Finished upload.
[Mon Oct  5 17:06:18 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /workdir/.snakemake/log/2020-10-05T170617.755391.snakemake.log
```
Importantly, notice how it generates the path of the output relative to the storage, even though it's on the filesystem of the "worker"
```bash
(snakemake) vanessa@testing-snakemake-touch:/workdir$ 
(snakemake) vanessa@testing-snakemake-touch:/workdir$ ls snakemake-testing/touch/
fileJob1
```
Now we run the second command

```bash
snakemake snakemake-testing/touch/fileJob2.txt --snakefile Snakefile --force -j --keep-target-files --keep-remote --latency-wait 0 --scheduler greedy --attempt 1 --force-use-threads --max-inventory-time 0  --allowed-rules job2 --nocolor --notemp --no-hooks --nolock  --default-remote-provider GS --default-remote-prefix snakemake-testing/touch  --default-resources "mem_mb=15360"  "disk_mb=512000" 
```
This leads to reproducing the error (good!)

```
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	job2
	1

[Mon Oct  5 17:10:02 2020]
rule job2:
    input: snakemake-testing/touch/fileJob1
    output: snakemake-testing/touch/fileJob2.txt
    jobid: 0
    resources: mem_mb=15360, disk_mb=512000

Hello World! -- job2
Waiting at most 0 seconds for missing files.
MissingOutputException in line 8 of /workdir/Snakefile:
Job completed successfully, but some output files are missing. Missing files after 0 seconds:
snakemake-testing/touch/fileJob2.txt
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
  File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 566, in handle_job_success
  File "/opt/conda/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 243, in handle_job_success
Removing output files of failed job job2 since they might be corrupted:
snakemake-testing/touch/fileJob1
```
We see that the correct storage path is there, so I don't think this issue is akin to Tibanna. I installed Snakemake locally (with -ppi -e) and then added an ipython.embed() where it looks like the error is coming from, [here](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/dag.py#L455) and note that io.py has a few other instances, but the error messages don't match what we see. First, for the working job. The expanded path derived from what is called the shadowed path is equivalent

```python
job
job1

list(job.expanded_output)
['snakemake-testing/touch/fileJob1']

job.shadowed_path(list(job.expanded_output)[0])
'snakemake-testing/touch/fileJob1'
```
ignore_missing_output is False, so we enter the loop (this should work here). The try/except for this command does not spit out an error to see the error we get for the next step.
```
wait_for_files(
                    expanded_output,
                    latency_wait=wait,
                    force_stay_on_remote=force_stay_on_remote,
                    ignore_pipe=True,
                )
```
Now let's step into this for the second step, the one with touch. Everything looks the same so far, and we can see the first file still exists (we assume that this would be obtained from storage for the second worker)
```
 job.expanded_output
<generator object Job.expanded_output at 0x7f4c3b71ef90>

list(job.expanded_output)
['snakemake-testing/touch/fileJob2.txt']

expanded_output = job.shadowed_path(list(job.expanded_output)[0])

expanded_output
'snakemake-testing/touch/fileJob2.txt'

# needs to be a list
expanded_output = [expanded_output]

ls snakemake-testing/touch
fileJob1
```

okay and now with the wait_for_files we reproduce the error.

```
----> 1 wait_for_files(
      2                     expanded_output,
      3                     latency_wait=wait,
      4                     force_stay_on_remote=force_stay_on_remote,
      5                     ignore_pipe=True,

/workdir/snakemake/io.py in wait_for_files(files, latency_wait, force_stay_on_remote, ignore_pipe)
    683                 return
    684             time.sleep(1)
--> 685         raise IOError(
    686             "Missing files after {} seconds:\n{}".format(
    687                 latency_wait, "\n".join(get_missing())

OSError: Missing files after 0 seconds:
snakemake-testing/touch/fileJob2.txt
```
That message is generated via the logic of [this function](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/io.py#L653) which does seem correct - the file isn't remove, doesn't exist, etc. It seems like the touch command didn't actually run as it should have? So when I add an interaction session to [touch](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/io.py#L500) it enters twice for the first working run, but doesn't enter at all for the second - it hits that MissingOutputException before any chance to be called. I also added an interactive session to [touch_or_create](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/io.py#L523) and it's never used. So I could be wrong but I don't think that editing the prefix is going to change the issue - the file is not created relatively or within the prefix folder, and I think the  issue comes down to when/how touch is used. So let's see if we can look at that. It looks like a job has a "touch output" parameter, strangely it's empty for this job2

```
job.touch_output
set()
```
It's derived from the rule touch output, but that's also empty:

```bash
job.rule.touch_output
set()
```
It seems like the logic happens [here](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/rules.py#L529), because the output should be flagged as "touch." If we look at the actual flags, it's flagged as a remote_object.

```python
item.flags
{'remote_object': <snakemake.remote.GS.RemoteObject at 0x7f46efd2f220>}
```
I think possibly because the prefix is added, and it's intended to be uploaded? Anyway, an issue I'm seeing is in the set_ouput function, there is no record of any kind that fileJob2.txt is a touch, and actually it looks exactly the same as the previous fileJob1

```python
self.dynamic_input
set()

output
: ('fileJob2.txt',)

self.dynamic_output
set()

self.touch_output
set()
```

Here https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/rules.py#L388. So I think this is more of a Snakefile parsing issue. So taking a look at where we call set_output, in [workflow.py](https://github.com/snakemake/snakemake/blob/9f1a81f831d0f64792370d82412a1e21342185ef/snakemake/workflow.py#L1179) in the decorator function. Again, I don't see any distinction between an output with or without touch. It's assuming that the shell statement will create it, I suspect.
```
ruleinfo.input
(('fileJob1',), {})

ruleinfo.output
(('fileJob2.txt',), {})
```
But I want to stop here, because I'm not sure I fully understand the purpose of touch. If you read the --help, it looks like these files were expected to exist, and clearly states that it would trigger an error otherwise.

```bash
 --touch, -t           Touch output files (mark them up to date without really changing them) instead of
                        running their commands. This is used to pretend that the rules were executed, in order
                        to fool future invocations of snakemake. Fails if a file does not yet exist. Note that
                        this will only touch files that would otherwise be recreated by Snakemake (e.g.
                        because their input files are newer). For enforcing a touch, combine this with
                        --force, --forceall, or --forcerun. Note however that you loose the provenance
                        information when the files have been created in realitiy. Hence, this should be used
                        only as a last resort. (default: False)
```
So - I think we need to ask others (@johanneskoester ?) how this is supposed to work. If it's supposed to act as the actual touch command then it likely is a bug with parsing the Snakefile and flagged it as such. If it's more of a hack to keep a workflow running given a previously existing file, then I think the simple solution is just to do it directly.

```
rule all:
    input: "fileJob2.txt"

rule job1:
    output: "fileJob1"
    shell: "echo Hello World -- job1 > {output}"

rule job2:
    input: "fileJob1"
    output: "fileJob2.txt"
    shell: "touch {output}"
```
That produces what you'd expect.

```
$ ls snakemake-testing/touch/
fileJob1  fileJob2.txt
```
I'll keep the instance around for a day or so in case anyone else wants me to test something. Thoughts or things to try appreciated!

**Comment by dcroote** [comment]
Interesting, it appears `--touch` on the command line differs from `touch()` in a rule output. From [flag files in the docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=touch#flag-files): 

> With the touch flag, Snakemake touches (i.e. creates or updates) the file mytask.done after mycommand has finished successfully.
<br />
@vsoch - I also think it's a parsing issue as the output is not being added to the `touch_output` sets:
<br />

### No default-remote
```
snakemake -j1
```

This completes successfully, touching the output as expected. When interactively debugging, the sets `job.touch_output` and `job.rule.touch_output` include the expected job2 output:
```
>job
job2
>job.touch_output
{'fileJob2.txt'}
>job.rule.touch_output
{'fileJob2.txt'}
```

### With default-remote
```
snakemake -j1 --default-remote-provider GS --default-remote-prefix sm-test-gs
```
Results in empty sets, which is what you saw @vsoch 
```
>job
job2
>job.touch_output
{}
>job.rule.touch_output
{}
```

Now, the question is, why isn't the output being added to `touch_output` in the first place? One clue is in `rules.py`
https://github.com/snakemake/snakemake/blob/9f8eb49af15b4d42183f8fd9914fa1e9477500fc/snakemake/rules.py#L497

The item, in this case `<default-remote-prefix>/fileJob2.txt` has only the key `remote_object` and not `touch`
```
>item
'sm-test-gs/fileJob2.txt'
>item.flags.keys()
dict_keys(['remote_object'])
```

whereas it does when running Snakemake without `default-remote`:
```
>item.flags.keys()
dict_keys(['touch'])
```

Ultimately, using `shell: "touch {output}"` will of course work, but at this point I feel we're close to finding the differences in paths taken when using remote and when not.

**Comment by vsoch** [comment]
Agreed @dcroote, and I'm glad that you reproduced what I found. Let's try figuring out where the flags are set then, or moreso, why touch doesn't seem to be. First I was looking at the [parser](https://github.com/snakemake/snakemake/blob/master/snakemake/parser.py#L873) for the snakefile, and I double checked that it's compilation includes touch (it does)

```python
...
@workflow.output( touch ( "fileJob2.txt" )
)
@workflow.shellcmd ( "echo RUNNING -- job2"

)
@workflow.run
def __rule_job2(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook):
	shell ( "echo RUNNING -- job2" , bench_record=bench_record, bench_iteration=bench_iteration
) 
```
And it looks like there must be a flag to print the compilation (good to know for next time)

```
if print_compilation:
            print(code)
```
Then we hop back over to the workflow function, where the code and line mapping is returned. I'm actually not totally clear on what this does, this [helped a bit](https://www.programiz.com/python-programming/methods/built-in/compile)

```
exec(compile(code, snakefile, "exec"), self.globals)
# compile
# <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>
````
and when we compile it seems that we jump into setting input and output. Actually I'll share the whole thing in case it's needed

<details>

```
@workflow.rule(name='all', lineno=1, snakefile='/workdir/Snakefile')

@workflow.input( "fileJob2.txt"
)

@workflow.norun()
@workflow.run
def __rule_all(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook):
	pass
@workflow.rule(name='job1', lineno=10, snakefile='/workdir/Snakefile')

@workflow.output( "fileJob1"
)
@workflow.shellcmd ( "echo Hello World -- job1 > {output}"

)
@workflow.run
def __rule_job1(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook):
	shell ( "echo Hello World -- job1 > {output}" , bench_record=bench_record, bench_iteration=bench_iteration
) 


@workflow.rule(name='job2', lineno=23, snakefile='/workdir/Snakefile')

@workflow.input( "fileJob1"
)

@workflow.output( touch ( "fileJob2.txt" )
)
@workflow.shellcmd ( "echo RUNNING -- job2"

)
@workflow.run
def __rule_job2(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook):
	shell ( "echo RUNNING -- job2" , bench_record=bench_record, bench_iteration=bench_iteration
) 
```

</details>

So if this is translated to python code and executed, we probably should look at the workflow decorator next, and figure out which line will parse the `@workflow.input` I first looked [here](https://github.com/snakemake/snakemake/blob/master/snakemake/workflow.py#L1382) and interactively checked the decorator function, but even by the time we get here the touch is removed

```
paths
('fileJob2.txt',)

kwpaths
{}
```
Ah finally some progress! When we are parsing the ruleinfo (for the first decorator) the output is an annotated string, and it still maintains the touch flag

```python
ruleinfo.output[0]
('fileJob2.txt',)

type(ruleinfo.output[0][0])
snakemake.io.AnnotatedString

ruleinfo.output[0][0].flags
{'touch': True}
```

Just found the bug, it's right at the self._set_inoutput_items. We start with an item annotated for touch, we end with one that is only annotated for a remote object.

```python
item.flags
{'touch': True}

item = self.apply_default_remote(item)

item.flags
{'remote_object': <snakemake.remote.GS.RemoteObject at 0x7eff74288640>}
```
I'll test out some potential fixes and see if I can open a PR.

**Comment by vsoch** [comment]
More detail - the error comes down to [this function](https://github.com/snakemake/snakemake/blob/master/snakemake/workflow.py#L457). The path variable to start is an annotated string, but when we format it into a proper fullpath we lose the annotations / flags.

**Comment by vsoch** [comment]
Please see https://github.com/snakemake/snakemake/pull/665
