### ISSUE TITLE
Develop a pipeline with snakemake for anaconda

### ISSUE THREAD

**Issue by iquasere** [snakemake/snakemake#644]
**Is your feature request related to a problem? Please describe.**
How to develop a pipeline based in snakemake in a way it can be submitted to Anaconda, and accessed remotely, without calling snakemake?

**Describe the solution you'd like**
I want to adapt my [pipeline ](https://bioconda.github.io/recipes/mosca/README.html) that is already available through bioconda to using snakemake - the main script would be converted into a Snakefile, and this snakefile could be called as a regular tool.

**Describe alternatives you've considered**
How should the Snakefile be configured to be run as a Conda tool?

**Comment by Maarten-vd-Sande** [comment]
This should be asked on stackoverflow, but to answer your question:

Take a look at https://github.com/vanheeringen-lab/seq2science (my work) or snakepipes (https://github.com/maxplanck-ie/snakepipes)

**Comment by Maarten-vd-Sande** [comment]
The parsing of samples and config is indeed a bit unclear.

The samples are "checked" in this part: https://github.com/vanheeringen-lab/seq2science/blob/master/seq2science/rules/configuration_generic.smk#L113

We check a couple things, like if it is filled in correctly. And for some of this we make use of sample schemas: https://github.com/vanheeringen-lab/seq2science/tree/master/seq2science/schemas/samples

Since the configuration file is included before the rest of the code it is executed before the samples are used in the lower part of the Snakefile. The actual sample file and configuration you pass to the seq2science command line interface, which passes it through the snakemake API to snakemake. Let me know if you need more help :+1:

**Comment by iquasere** [comment]
How do you iterate over the pandas DF for every rule? As an example, when I want to run 
```
import pandas as pd

configfile: "config.json"

experiments = pd.read_csv(config["experiments"], sep = '\t')

rule all:
  input:
    expand("{output}/Assembly/{experiment[1][Sample]}/contigs.fasta", 
            output = config["output"], experiment = experiments)
```
it says 
```
TypeError in line 10 of /path/to/Snakefile:
string indices must be integers
  File "/path/to/Snakefile", line 10, in <module>
```
This makes sense, but how can I access the values in each line? Are the iterator methods, like read_table, required?

**Comment by iquasere** [comment]
I did follow you advise and raised the same question over at [StackOverflow ](https://stackoverflow.com/questions/64340217/converting-a-large-pipeline-to-snakemake/64376413#64376413) :)

**Comment by iquasere** [comment]
Moved to StackOverflow
