### ISSUE TITLE
Snakemake does not automatically create directories when using `directory(..)`

### ISSUE THREAD

**Issue by kpj** [snakemake/snakemake#774]
**Snakemake version**
5.30.1

**Describe the bug**
When using the `directory(..)` function to set output directories, Snakemake does no longer automatically create them.
This leads to crashes when writing to files which are supposed to be in this directory.

**Minimal example**
Consider the following Snakefile:
```python
rule all:
  input: 'foo/'

rule baz:
  output: directory('foo/')
  shell: "touch {output}/bar.txt"
```

In an older version (`5.26.1`) of Snakemake, this works just fine:
```bash
$ snakemake --version
5.26.1
$ snakemake -j
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	baz
	2

[Fri Nov 27 12:50:21 2020]
rule baz:
    output: foo/
    jobid: 1

[Fri Nov 27 12:50:21 2020]
Finished job 1.
1 of 2 steps (50%) done

[Fri Nov 27 12:50:21 2020]
localrule all:
    input: foo/
    jobid: 0

[Fri Nov 27 12:50:21 2020]
Finished job 0.
2 of 2 steps (100%) done
```

However, in the latest version (`5.30.1`) this crashes:
```bash
$ snakemake --version
5.30.1
$ snakemake -j
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	baz
	2

[Fri Nov 27 12:51:03 2020]
rule baz:
    output: foo
    jobid: 1

touch: foo/bar.txt: No such file or directory
[Fri Nov 27 12:51:03 2020]
Error in rule baz:
    jobid: 1
    output: foo
    shell:
        touch foo/bar.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by nhartwic** [comment]
I get that changing behavior sucks, I think this was a good change. Rules should be responsible for creating the described output, not snakemake. Snakemake doesn't touch output files, so why would it make output dirs?

From a practical perspective, there are tools out there which expect to be pointed to a location that doesn't already exist. If a directory already exists, the tool will assume its a pre-existing output and will error out instead of risk overwriting something. It is a lot easier for a user to update their code to create the directory than it is for a user to update some elses code to work properly when pointed to an empty directory.

You could easily change your rule to...

```
rule baz1:
  output: directory('foo/')
  shell: "mkdir -p {output} && touch {output}/bar.txt"
```

...You could argue that it is similarly easy to handle weird tools using something like...

```
rule baz2:
  output: directory('foo/')
  shell: "rmdir {output} && sometool -o {output}"
```
...But then it comes back to the design philosophy at the start and personal intuition. Personally, I think the baz1 command is easier to grok than the baz2 command.

**Comment by kpj** [comment]
Thanks for your response!

If this is an intended change, I can totally understand the reasoning and tend to agree with it :)
I was mostly concerned because I couldn't find anything about it in the Changelogs.

**Comment by macieksk** [comment]
This change in behavior is actually due to a change in right stripping "/" in `snakemake/io.py:_IOFile::__new__` . There `file.rstrip("/")` changes directory creation code in `snakemake/io.py:_IOFile::prepare` . 
Not sure if this was intended.

The old behavior for directory creation can be restored with the following patch:
```diff
diff --git a/snakemake/io.py b/snakemake/io.py
index 80d64621..1b7b71bd 100755
--- a/snakemake/io.py
+++ b/snakemake/io.py
@@ -608,7 +608,10 @@ class _IOFile(str):
             logger.info("Finished upload.")
 
     def prepare(self):
-        path_until_wildcard = re.split(DYNAMIC_FILL, self.file)[0]
+        if self.is_directory:
+            path_until_wildcard = re.split(DYNAMIC_FILL, self.file+"/")[0]
+        else:
+            path_until_wildcard = re.split(DYNAMIC_FILL, self.file)[0]
         dir = os.path.dirname(path_until_wildcard)
         if len(dir) > 0:
             try:
```

Outputs marked as `directory(...)` are removed before rule run or after a failed run, with or without the above patch.

**Comment by macieksk** [comment]
@johanneskoester Would you like to comment on the above fix? Should it be applied as a patch fix?

**Comment by enryH** [comment]
I also ran into this. If you specify a file as output, the directories which should contain the file are created by snakemake.
