### ISSUE TITLE
"SyntaxError" for the Snakefile located in the directory which name cntains an apostrophe symbol

### ISSUE THREAD

**Issue by dkuzminov** [snakemake/snakemake#85]
Environment: Snakemake 5.4.5, Python 3.6.5, Windows 10, MinGW.

Way to reproduce: take a fully valid project and put into a directory that has an apostrophe in it’s name, e.g. “I’ll not work“, try to run. The Snakemake raises an SyntaxError “invalid syntax“ on the first rule found. Rename the directory back and remove the apostrophe, e.g. “I will work“, the project works again.

**Comment by SichongP** [comment]
This is because in `workflow.py` it calls `exec(compile(code, snakefile, "exec"), self.globals)`
The `snakefile` variable in this code contains the path to your Snakefile, which contains an apostrophe. The apostrophe is parsed literally and interpreted by python as a quote, causing syntax error. 

Easy fix is just to remove the apostrophe in file path, like you've discovered. In general it is bad practice to use characters like `"`, `'`, ` `(space) in your file or path names because these characters usually hold special places in programs.

**Comment by dkuzminov** [comment]
I agree that it is a minor issue but Snakemake shouldn't depend on the path of the project folder. The symbols like apostrophe should be escaped before the `exec` invocation, moreover it shouldn't be a confusing SyntaxError. Anyway there must be other problems caused by not escaping symbols before `exec` invocation.

**Comment by tbooth** [comment]
Hi,
Actually the call in `workflow.py` fails because of the value of `code`, not because of the value of `snakefile`. The root cause is in the `parser.py` module:

```
    snakefile=self.snakefile.path.replace('\\', '\\\\')
```

After this partial escaping, the resulting string is enclosed in single quotes. It seems to me this logic should simply be replaced by repr() which robustly quotes strings for use in Python code, and a quick test confirms this seems to fix the issue. I can see several other instances in this file that appear to be crying out for `repr(foo)` instead of 
`'"{}"'.format(foo)` so I'm going to try and prepare a full PR with all of them fixed.
