### ISSUE TITLE
Suggested solution to lints

### ISSUE THREAD

**Issue by colinbrislawn** [snakemake/snakemake#880]
I've started to to use `--lint` to clean up my workflow, and it's been very helpful! 🧹 

However, I'm having trouble finding a good solution for one line and would appreciate any guidance.
(If this is out of scope or should be posted elsewhere, feel free to close this issue.)

**How can I improve this line?**
```python
SAMPLES, = glob_wildcards(config.get("folder")+"/{sample}."+config.get("file_type", "fastq.gz"))
```

My current method creates two lints:
```
* Absolute path "/{sample}." in line 10:
      Do not define absolute paths inside of the workflow, since this renders
      your workflow irreproducible on other machines. Use path relative to the
      working directory instead, or make the path configurable via a config
      file. Also see: https://snakemake.readthedocs.io/en/latest/snakefiles/configuration.html#configuration

* Path composition with '+' in line 10:
      This becomes quickly unreadable. Usually, it is better to endure some
      redundancy against having a more readable workflow. Hence, just repeat
      common prefixes. If path composition is unavoidable, use pathlib or
      (python >= 3.6) string formatting with f"...".
      Also see:
```

The intended result is a list of strings:
```python
> print(SAMPLES)
['sample1', 'sample2']
```

Thanks!

**Comment by HenningTimm** [comment]
I just found this issue in a mostly unrelated google search. While I don't think, this will still be helpful to @colinbrislawn I will try to answer for other people and close this. Sorry it took a year and a half.

The two things the linter is complaining about are:
- The string `"/sample"` is interpreted by the linter as an absolute path. We will get the fix for this for free.
- Assembling the path using string concatenation with `+` can get a bit confusing. The best way to do this (as suggested by the linter) is using a format string, as they look a bit cleaner.

With a format string, the line would look as follows:
```python
SAMPLES, = glob_wildcards(f"{config.get('folder')}/{{sample}}.{config.get('file_type', 'fastq.gz')}")
```
The leading `f` denotes it is a format string. The values for `"folder"` and `"file_type"` are formatted directly into the string. In order to keep `{sample}` in the final string that is passed to `glob_wildcards`, we need to escape the curly braces as `{{sample}}` which will come out as `{sample}` after the formatting is done. Since the string with the leading `/` is no longer in there, this refactoring also fixes the first lint.

> (If this is out of scope or should be posted elsewhere, feel free to close this issue.)
I think the best chance to get answers for questions like this currently is stackoverflow. 

I hope this helps anyone ;)

**Comment by vinisalazar** [comment]
Hi @HenningTimm,

Thanks for providing this answer. I'd like to report that I am facing the same problem while having the following `awk` command as my shell directive:

```awk
awk '/^>/{{gsub(" |\\\\.|=", "_", $0); print $0; next}}{{print}}' {input} > {output}
```

I get this from the linter:

```
Lints for snakefile /path/to/file.smk:
    * Absolute path "/^>/{{gsub(" |\\\\.|=", "_", $0); print $0; next}}{{print}}" in line 99:
      Do not define absolute paths inside of the workflow, since this
      renders your workflow irreproducible on other machines. Use path
      relative to the working directory instead, or make the path
      configurable via a config file.
      Also see:
      https://snakemake.readthedocs.io/en/latest/snakefiles/configuration.html#configuration
```

I bypassed this by having the awk command as a setting in my config and then using `config["awk_command"]` as my shell directive, but I think this adds unneeded complexity to my code (I had to add this new setting to my config schema and so on).

Would it be possible to maybe add a comment string that disables certain lines for the linter?

Thank you for any assistance you can provide!
V

**Comment by hepcat72** [comment]
I'm having an issue with the "path composition" using `+` issue, but if I convert the line to an f-string, it breaks the code... because the `+` is being used with a pandas dataframe:
```
# Read in and validate the sample table
sample_data = pd.read_table(config["sample_data"])
validate(sample_data, schema="schemas/sample_data.schema.yml")
# Add a column named "biol_rep_sample" with values: f"{sample_name}_{biol_rep_id}"
sample_data["biol_rep_sample"] = sample_data["sample_name"] + "_" + sample_data['biol_rep_id'].map(str)
```
How do I satisfy the linter AND have working code?

**Comment by niekwit** [comment]
Hi @hepcat72, I had a similar issue. I got around it with the following:
```
sample_data["biol_rep_sample"] = sample_data[["sample_name", "biol_rep_id"]].agg('_'.join, axis=1)
```
This solved the linting issue.
